### ISSUE TITLE
[Feature Request] View pending changes before publishing

### ISSUE THREAD

**Issue by zbs** [cvmfs/cvmfs#2615]
`cvmfs_server diff` will allow you to view the diff between published snapshots; however, it would be useful as a sanity check to see the diff of the pending changes.

**Comment by siscia** [comment]
Thanks, we are actually considering something similar, but I don't believe we got any ETA at the moment.

However, you should be able to have a comprehensive overview of what happens in the filesystem by looking into: `/var/spool/cvmfs/$repo.name.com/scratch/current/`

Does this helps?

Cheers,
Simone

**Comment by zbs** [comment]
That helps for now. Thank you.

I think eventually a full diff view (lines added/changed/removed) would give a more helpful, complete view, but in the interim, this works fine.

**Comment by siscia** [comment]
We agree!

I am closing this for now, since we don't use GitHub issues for tracking.

We really appreciate the feedback and the idea , in this particular case, it was already on our radar.
