### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by pedro-vicente** [cvmfs/cvmfs#2620]
Doing a simple git clone on Windows , this error comes up

> 

git.exe clone --progress -v "https://github.com/cvmfs/cvmfs" "M:\cvmfs"
Cloning into 'M:\cvmfs'...
POST git-upload-pack (gzip 7625 to 3546 bytes)
remote: Enumerating objects: 310, done.
remote: Counting objects: 100% (310/310), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 91087 (delta 180), reused 216 (delta 115), pack-reused 90777
Receiving objects: 100% (91087/91087), 160.61 MiB | 10.80 MiB/s, done.
Resolving deltas: 100% (65485/65485), done.
error: invalid path 'test/unittests/aux/tar_files.h'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by siscia** [comment]
Hi,

thanks for opening the issue.

Unfortunately windows is not a supported platform.

What are you trying to achieve?

Cheers,

**Comment by pedro-vicente** [comment]
Yes, I know Windows is not supported;
But I just wanted to do a "git clone" to a Windows machine;
"git clone" just copies the repo to that computer

The goal is just to look at the code , since the project seems interesting (eventually a Windows port could be done)

I was under the impression that "git clone" just replicates the file structure locally, curious about where the path 

error: invalid path 'test/unittests/aux/tar_files.h'

comes from

**Comment by siscia** [comment]
Honestly this error leave me wondering as well.

The file contains few base64 encoded tarfiles. I guess it can somehow be problematic for windows...

**Comment by jblomer** [comment]
One way to work with cvmfs on Windows is WSL2.  You should be able to clone, compile, and run cvmfs under WSL2 as described in #2601

**Comment by jblomer** [comment]
Closing, please feel free to reopen if necessary.
