### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by steve8x8** [cvmfs/cvmfs#2660]
Debian Bullseye, to be released in a few months, will supposedly drop Python2, making `python3` the only `python`. Is it planned to replace Python2 with Python3? There are no Bullseye builds available from the packagecloud yet (neither are arm64 builds, which was the primary reason why I'm looking into building myself at all).

A build attempt with `python3-all-dev` and `python3-setuptools` in the `Build-Depends:` results in a "cannot import name 'Feature' from 'setuptools'" in MaxMindDB, an error that was fixed in Debian's version 1.4.1 (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959544 for details and a link to the patch applied).
CVMFS 2.7.5 comes with MaxMindDB 1.4.0 ... but the patch can easily be modified.

(Another issue with MaxMindDB is that `maxminddb/extension/maxminddb.c` `#include`s `<maxminddb.h>` which isn't provided.)

Any advice?

**Comment by DrDaveD** [comment]
I think that cvmfs probably doesn't use maxminddb/extension/maxminddb.c; have you see it cause any errors?

If we need to apply a patch to MaxmindDB we might as well upgrade to 1.4.1 at the same time.

The next thing that we'll run across is that the geo api under cvmfs/cvmfs/webapi has not yet been ported to python3.

**Comment by DrDaveD** [comment]
I think that cvmfs probably doesn't use maxminddb/extension/maxminddb.c; have you see it cause any errors?

If we need to apply a patch to MaxmindDB we might as well upgrade to 1.4.1 at the same time.

The next thing that we'll run across is that the geo api under cvmfs/cvmfs/webapi has not yet been ported to python3.

**Comment by DrDaveD** [comment]
I see this problem was fixed in [1.5.0](https://github.com/maxmind/MaxMind-DB-Reader-python/commit/3aac426e354f91814f6fd0829baee137b0bb093f).  The latest version in the 1.x.x series is 1.5.4.  There's a 2.0.x version now too but we probably don't want that at this point.

**Comment by steve8x8** [comment]
Are there plans to release cvmfs depending on a fixed maxminddb in the near future?

**Comment by DrDaveD** [comment]
I see there's a [JIRA ticket for updating the geo api to python3](https://sft.its.cern.ch/jira/browse/CVM-1757) but it hasn't been assigned to any release yet.

**Comment by boegel** [comment]
GeoAPI was ported to Python 3 in #2829 (includes in upcoming CernVM-FS 2.9.1 release), so this can be closed?

**Comment by DrDaveD** [comment]
I agree, this can be closed.
