### ISSUE TITLE
cvmfs tarball creation for ecsft

### ISSUE THREAD

**Issue by skluth** [cvmfs/cvmfs#2697]
Currently, the cvmfs.tar.gz in https://ecsft.cern.ch/dist/cvmfs/ is created by a script in cvmfs/ci. This is okish, but a bit unusual, as it creates a tarball unpacking to cvmfs/... as expected by external build systems (OBS, COPR). I naiively thought downloading the tar.gz from this github repo would be sufficient, but it gives a tarball unpacking to cvmfs/cvmfs/... failing on external platforms.

I didn't find a script which is responsible for populating ecsft.cern.ch/dist/cvmfs. If such a script exists, it could be modified to also copy the spec file as cvmfs.spec, possibly with versioning.

**Comment by jblomer** [comment]
Release tarballs and packages are provided on http://ecsft.cern.ch/dist/cvmfs/ and https://cvmrepo.web.cern.ch/cvmrepo/, with the scripts available in this repo and, for steering, in https://github.com/cernvm/ci-scripts. The github releases page is empty (as it should). Tarballs are still created for every tag, I don't think this can be disabled.

Closing this for the time being, please feel free to reopen if needed.
