### ISSUE TITLE
CVMFS nioerr xattr not working?

### ISSUE THREAD

**Issue by bbockelm** [cvmfs/cvmfs#2712]
In OSG, we've started to plot the nioerr xattr for each running pilot.  The idea is that we can quickly detect errors 

Suspiciously, across the entire grid, we've never seen this counter go above zero - despite an occasional bad host that causes a large number of jobs to fail with `EIO`.

Any clue if this counter actually functions?  A quick scan through the code suggests that there might at least be some code paths where it isn't incremented (failures in opening chunks, for example) for file opens and it's not incremented if the EIO occurs for lookups, readdirs, or stats.

**Comment by jblomer** [comment]
That counter is a bit sloppy, unfortunately.  We should go systematically through the fuse callbacks and make sure we catch all the error replies. See [CVM-2006](https://sft.its.cern.ch/jira/browse/CVM-2006)

**Comment by bbockelm** [comment]
An update from our side -- it seems the monitoring implementation was checking `NIOERR` (not the correct name) instead of `nioerr` (the correct name) and defaulting to `0` on error.  Hence, our original suspicions were just from poorly tested code.

That said, I think the diagnosis of missing a few less-common cases is absolutely correct.
