### ISSUE TITLE
document how to mount a specific tag

### ISSUE THREAD

**Issue by innovate-invent** [cvmfs/cvmfs#2749]
The documentation mentions how to create and manage tags from the server side, but makes no mention on how to configure targeting a specific tag when mounting the client.

https://github.com/cvmfs/doc-cvmfs/blob/latest/cpt-repo.rst#named-snapshots

**Comment by jblomer** [comment]
Thanks for bringing this up!  The corresponding client parameter is `CVMFS_REPOSITORY_TAG=$tagname`.  We'll update the documentation accordingly.

**Comment by HereThereBeDragons** [comment]
thanks again for reporting it. good documentation always helps. closed now as added to the doc
