### ISSUE TITLE
ENV CVMFS_HTTP_PROXY=DIRECT must be in caps, but ENV CVMFS_CLIENT_PROFILE=single doesn't

### ISSUE THREAD

**Issue by rklasen** [cvmfs/cvmfs#2823]
Hi,

I just stumbled over this distinction. Is there a reason the "DIRECT" keyword has to be in caps, while the "single" doesn't?

Best wishes!

**Comment by radupopescu** [comment]
Hi,

There isn't any reason, unfortunately it's an inconsistency.

Thanks!
