### ISSUE TITLE
incompatibility with newer versions of libattr

### ISSUE THREAD

**Issue by cburgard** [cvmfs/cvmfs#2826]
When trying to compile on my latest archlinux, I get this

```
CMake Error at CMakeLists.txt:284 (message):
  attr/xattr.h is missing on your system
Call Stack (most recent call first):
  CMakeLists.txt:292 (pedantic_include_check)
  CMakeLists.txt:317 (look_for_include_files)
```

**Comment by jblomer** [comment]
Probably an issue only in the `CMakeLists.txt` file, I think the code should compile if the check for xattr.h was simply removed.

**Comment by jblomer** [comment]
@cburgard Is this the latest version of cvmfs?  Checking the `CMakeLists.txt` file, the xattr.h is an optional header. I also cannot reproduce the failure on my arch system.

**Comment by cburgard** [comment]
Updating to the latest versions both on my system and for CVMFS did the trick, thanks for following up!
