### ISSUE TITLE
cvmfs_ducc: support `application/vnd.oci.image.manifest.v1+json` manifest

### ISSUE THREAD

**Issue by Darkness4** [cvmfs/cvmfs#2851]
Hello,

If we build and push an image with podman or buildah to a local registry, executing `cvmfs_ducc convert` would cause the following error :

```sh
{ "errors":[{ "code": "MANIFEST_UNKNOWN", "message": "OCI manifest found, but accepted header does not support OCI manifests"}]}

ERRO[0001] Error in getting manifest to determine singleton path error="Got empty manifest"
WARN[0001] Error in obtaining the path to save the Singularity file system: Got empty manifest error="Got empty manifest"
ERRO[0001] Error in converting wish (singularity), going on error="Error in getting the path where to save Singularity filesystem : Got empty manifest" input image="http://localhost:5000/library/symbolic-link:latest" output image="http://registry.fake/thin/library/symbolic-link:latest" repository=unpacked.fake
```

This is because podman and buildah use an OCI manifest by default.

On the client side, this can be fixed by using :

```sh
podman build -t <tag> --format docker .
# For buildah
buildah commit --format docker "$ctr" "<tag>"
```

On the cvmfs_ducc side, it would be great if DUCC could support `application/vnd.oci.image.manifest.v1+json`.

https://github.com/cvmfs/cvmfs/blob/e54432cbd2deb065947b6f7f1f28ca0765019461/ducc/lib/image.go#L178

The documentation of the OCI manifest is written here: https://github.com/opencontainers/image-spec/blob/main/manifest.md

**Comment by jblomer** [comment]
From the current wishlist, this can be tested, e.g., with `https://registry.hub.docker.com/rodwalker/teec:0.1`

**Comment by jblomer** [comment]
At the same time, reporting should be fixed so that it pinpoints which image of an expanded specification is affected
