### ISSUE TITLE
New pacparser version 1.3.9 available

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2872]
[pacparser 1.3.8](https://github.com/manugarg/pacparser/releases/tag/v1.3.8) has been released.  Update to that version when convenient.

**Comment by DrDaveD** [comment]
There's another new [pacparser release 1.3.9](https://github.com/manugarg/pacparser/releases/tag/v1.3.9) that among other things did a lot of python fixes so hopefully it will pass the tests now.

**Comment by radupopescu** [comment]
#2963 updates Pacparser to version 1.3.8 - this version compiles on newer macOS targets while maintaining compatibility with Python < 3.7 which is used on some of our older targets.

Once we do a cleanup of target platforms, we can revisit Pacparser and try to update to 1.4.0.

I suggest we close this ticket for now.
