### ISSUE TITLE
cvmfs mount segmentation fault in macos 1015 github-actions

### ISSUE THREAD

**Issue by andresailer** [cvmfs/cvmfs#2882]
Since about 1 week ago the github actions running on macos 1015 and mounting CVMFS repositories are failing with

https://github.com/AIDASoft/DD4hep/runs/5724820416?check_suite_focus=true#step:3:155
```
mount: /Users/Shared/cvmfs/sft.cern.ch: Segmentation fault
mount: /Users/Shared/cvmfs/geant4.cern.ch: Segmentation fault
Error: Process completed with exit code 69.
```

I tried using older cvmfs releases e.g., https://github.com/AIDASoft/DD4hep/pull/900
as there was a new cvmfs-latest.pkg file on March 23  but that didn't help.

Between the last successful run and the failures I see this difference in the update version of macos

working: https://github.com/AIDASoft/DD4hep/runs/5631738281?check_suite_focus=true#step:1:3
```
  Mac OS X
  10.15.7
  19H1713
```
Failing: https://github.com/AIDASoft/DD4hep/runs/5681443820?check_suite_focus=true#step:1:5
```
  Mac OS X
  10.15.7
  19H1824
```

Of course there could be other causes of why this fails, but I don't have a good way of testing against different macos versions.
Here is the diff for the macos used in github actions,  maybe something is apparent to you:
https://github.com/actions/virtual-environments/commit/5a140881dfe066c0878c62e0e7963c4d5c276f14

**Comment by radupopescu** [comment]
I've installed CVMFS 2.9.2 on my Macbook running macOS 12.3 and I can't reproduce the segmentation fault. I will try to find a machine with macOS < 12 to test.

Would it be possible to upgrade at least to Big Sur (11)? macOS 10.15 is not supported any longer.

**Comment by andresailer** [comment]
Ah, I didn't even know that 1015 wasn't supported any longer. Let's see in https://github.com/cvmfs-contrib/github-action-cvmfs/pull/15 if mac11 works, and we can move to that.

**Comment by radupopescu** [comment]
With Apple, only the previous OS version still receives updates.

**Comment by radupopescu** [comment]
I think almost all devices supported by 10.15 should also be supported by 11.

**Comment by andresailer** [comment]
wikipedia says supported https://en.wikipedia.org/wiki/MacOS_Catalina , but no citation :)

**Comment by wdconinc** [comment]
I think MacOS 11 needs some additional system-level permissions for fuse/cvmfs that are not available in the macos-11 image that github uses. At least that was the situation wen macos-11 was initially rolled out as default.

**Comment by wdconinc** [comment]
Yea, https://github.com/cvmfs-contrib/github-action-cvmfs/runs/5757772533?check_suite_focus=true#step:3:156 macos-11 fails differently with
```
Failed loading macFUSE
mount: /Users/Shared/cvmfs/sft.cern.ch failed with 1
```

**Comment by radupopescu** [comment]
> wikipedia says supported https://en.wikipedia.org/wiki/MacOS_Catalina , but no citation :)

Indeed, it seems 10.15.7 received some security patches in March.

I checked our CMake configuration, and we have 10.14 as minimum version. We didn't drop any support from our side.

**Comment by radupopescu** [comment]
I tried CVMFS 2.9.2 on a Mac mini (2018) running macOS 10.15.7. No segmentation fault so far.

**Comment by andresailer** [comment]
The same patch version 19h1824 as in github actions?

**Comment by radupopescu** [comment]
Build version is 19H2. Updating now

**Comment by radupopescu** [comment]
Now it's at 19H1824 (the update contained  Command Line Tools for Xcode, macOS Catalina Security Update 2022-003, Safari) and I get the segmentation fault.

**Comment by bedroge** [comment]
We were also seeing the `Failed loading macFUSE` with our EESSI Github runners running macOS 11, so we switched to macOS 10 a few weeks ago. But those now fail too due to the segmentation faults. I was debugging the issue on a macOS 10 VM on AWS, and I guess the issue may be similar to the macOS 11 issue now:
```
% sudo /Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse                            
% echo $?
1

% sudo kextload /Library/Filesystems/macfuse.fs/Contents/Extensions/10.16/macfuse.kext            
/Library/Filesystems/macfuse.fs/Contents/Extensions/10.16/macfuse.kext failed to load - (libkern/kext) system policy prevents loading; check the system/kernel logs for errors or try kextutil(8).
```

There's also lots of discussion about this on both the osxfuse repo and the github action repo:
https://github.com/osxfuse/osxfuse/issues/828
https://github.com/actions/virtual-environments/issues/4731
https://github.com/actions/virtual-environments/issues/598
But, unfortunately, there doesn't seem to be a solution for this yet...

**Comment by radupopescu** [comment]
I am no longer able to reproduce the segmentation fault on our macOS 10.15.7 machine, with Xcode 12.4. This is the most recent toolchain version supported on macOS 10.15, but has a bug in the include resolution, when the `cmath` header is included. There is a work-around, however: https://github.com/cvmfs/cvmfs/issues/2888

**Comment by andresailer** [comment]
Does this mean you have a new build of cvmfs that no longer exhibits the segmentation fault?

Or just updating xcode is sufficient to solve the problem? (we don't need the header workaround at runtime of cvmfs, right?)
What version of xcode compared to the one used by the github actions?
https://github.com/actions/virtual-environments/blob/06446ddb68fa8afa21cd8d2676a1757cbf6e9ce3/images/macos/macos-10.15-Readme.md?plain=1#L116
```
- Xcode Command Line Tools 12.4.0.0.1.1610135815
```

https://github.com/actions/virtual-environments/blob/06446ddb68fa8afa21cd8d2676a1757cbf6e9ce3/images/macos/macos-10.15-Readme.md?plain=1#L252
```
| Version        | Build    | Path                           |
| -------------- | -------- | ------------------------------ |
| 12.4 (default) | 12D4e    | /Applications/Xcode_12.4.app   |
```

**Comment by radupopescu** [comment]
Actually I spoke a bit too soon. With the workaround (which is only a hack) a third-party dependency of CVMFS doesn't compile and would need a patch.

It's not clear to me yet if the segmentation fault went away because of the new build.

I'll update the macOS Catalina node to macOS Big Sur 11 and will make a new build that you can try. FYI, if the upgrade to macOS 11 requires some Recovery Mode intervention, I'll only be able to finish this on Monday.

**Comment by radupopescu** [comment]
There is a new build of the CVMFS 2.9.2 macOS package available: https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.9.2/cvmfs-2.9.2.pkg

Please try it and let me know if the issue persists in your environments.

**Comment by andresailer** [comment]
Still fails.
downloading the new package is here: https://github.com/AIDASoft/DD4hep/runs/6384883737?check_suite_focus=true#step:3:4

**Comment by radupopescu** [comment]
Does it fail for macOS 11 or 12, too?

**Comment by andresailer** [comment]
I need more time to set up the job for mac11.

**Comment by andresailer** [comment]
cvmfs mount also fails on mac11: https://github.com/AIDASoft/DD4hep/runs/6387022757?check_suite_focus=true

**Comment by radupopescu** [comment]
Thanks for checking. This looks like a different error, though, seems related to macFUSE. Let me look into it and get more info

**Comment by radupopescu** [comment]
Are the Mac nodes running the CI for the AIDASoft project hosted by GitHub or are they machines under your control?

**Comment by andresailer** [comment]
The mac nodes are provided by github.

**Comment by andresailer** [comment]
You can see all the details: https://github.com/actions/virtual-environments/blob/macOS-11/20220501.1/images/macos/macos-11-Readme.md

**Comment by DrDaveD** [comment]
I also got `Segmentation fault` trying to mount, on macos 10.15.7

**Comment by tmadlener** [comment]
I am not entirely sure what changed, but mac workflows started working again for podio, see https://github.com/AIDASoft/podio/actions/workflows/mac.yml (the most recent ones that are failing are genuine CI failures)

**Comment by andresailer** [comment]
Another update on macos 10.15: 19H1922 seems to have fixed it :shrug: :partying_face:
