### ISSUE TITLE
DUCC: dependence on singularity?

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/cvmfs#2884]
Hello,

Does DUCC have a dependence on Singularity, and if so will it be changed to use Apptainer instead?

Based on some old notes from Simone I just did `dnf install singularity`  however I am not sure if installing the executable is still needed, or if the use of singularity is only via libraries in the code?

If the singularity (or apptainer) package is required it should be a dependency of the RPM.

Thanks!

**Comment by jblomer** [comment]
In the latest container conversion tools, there is no need to have singularity installed anymore. The conversion is done entirely by `cvmfs_ducc convert` itself.

**Comment by rptaylor** [comment]
Great, that is much better than requiring an external executable! 
I see there are a lot of references to singularity in the code; I'll leave it up to you to consider whether it should be migrated to apptainer.
