### ISSUE TITLE
Over 2100 missing catalog files from cms.cern.ch on a stratum 1

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2887]
The stratum 1 at UNL that is currently the primary server had over 2100 missing cms.cern.ch catalogs today.  The other identical server that is currently the backup had downloaded them all over a period of 7 minutes, between 06:48 and 06:55 U.S. Central time on April 2.  The new Australian stratum 1 reads from the primary UNL stratum 1, and I wrote a script to identify the 404 errors from there on the UNL stratum 1 squid log and then download the missing files from the backup stratum 1.  It took over 6 hours to complete.

The primary is running cvmfs-server-2.8.1 and the backup is running 2.9.2.  I looked through /var/log/messages and the cms.cern.ch snapshot log during the period in question and did not see any unusual messages.  However the fact that they were all catalogs has to be significant.  I don't think it is likely to be a problem with the filesystem.  Perhaps the filesystem returned some kind of error to cvmfs_swissknife once but I think it must have caused some kind of side effect in cvmfs_swissknife that resulted in cascading errors related only to catalogs.  On the other hand I guess it's possible that CMS did some type of operation that impacted only catalogs, but it seems unlikely.

There is plenty of disk space on the stratum 1 so it's not that. There's 31T/46% available in /storage (which contains both /srv/cvmfs and /var/spool/cvmfs/*/tmp), 199G/89% in /, and 1.5G/95% in /tmp.

**Comment by jblomer** [comment]
I think it's likely an issue that was fixed in [version 2.9.0](https://github.com/cvmfs/cvmfs/blob/devel/ChangeLog#L51) with [this patch](https://github.com/cvmfs/cvmfs/pull/2768/commits/b64ba577a70fd4e28d555e07d5c1ad697984498e#diff-804a6ef7dbb0a0731874df8fd06c6a803fa0d7bf76a62967d1a1792d484a489bR476).  It fixes a behavior where a new file system revision is installed even if some of the new chunks could not be properly stored in the backend.

We didn't see this problem in the wild back at the time, so unfortunately we did not point out clearly enough this fix.

@smuzaffar Do you recall any operation on the cms.cern.ch operation on April 2nd that might have modified a large number of catalogs?

**Comment by smuzaffar** [comment]
Yes @jblomer, on 2nd I installed cmssw version and during the installation I noticed that cvmfs publish complained about some catalogs with too many files [a] and to fix this I added [b] in /cvmfs/cms.cern.ch/.cvmfsdirtab . I think there is still some update needed in /cvmfs/cms.cern.ch/.cvmfsdirtab as old archs ( `slc7*gcc*` ) also now warns about large catelogs [c]



[a]
```
WARNING: catalog at /cs8_amd64_gcc10 has more than 500000 entries (1409823). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
WARNING: catalog at /cs8_ppc64le_gcc11 has more than 500000 entries (1402612). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
WARNING: catalog at /cc8_amd64_gcc9 has more than 500000 entries (2805695). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
WARNING: catalog at /alma8_amd64_gcc10 has more than 500000 entries (513153). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.

```

[b]
```
/cc*gcc*/cms/cmssw/*
/cc*gcc*/cms/cmssw-patch/*
/cc*gcc*/external/*/*
/cs*gcc*/cms/cmssw/*
/cs*gcc*/cms/cmssw-patch/*
/cs*gcc*/external/*/*
/alma*gcc*/cms/cmssw/*
/alma*gcc*/cms/cmssw-patch/*
/alma*gcc*/external/*/*
```

[c]
```
WARNING: catalog at /slc7_amd64_gcc900 has more than 500000 entries (585620). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
WARNING: catalog at /slc7_amd64_gcc820 has more than 500000 entries (512488). Large catalogs stress the CernVM-FS transport infrastructure. Please split it into nested catalogs or increase the limit.
```

**Comment by DrDaveD** [comment]
I have upgraded the server to 2.9.2 and started a `cvmfs_server check -a` on it to find out what else might be missing.  I'll close the ticket, and if it happens again I'll plan to reopen it.
