### ISSUE TITLE
Create a build of the CVMFS service container for arm64

### ISSUE THREAD

**Issue by radupopescu** [cvmfs/cvmfs#2889]

**Comment by radupopescu** [comment]
The current method of building the service container involves calling the host Docker from inside the builder container. This approach does not work on macOS, where we would need to build the arm64 container.

We could explore updating the build container to CentOS Stream 9 (current CentOS 8) and call buildah directly inside the container.

**Comment by vvolkl** [comment]
We do have recent arm64 build nodes now that could do this, but I only know of a handful users of the service container, and an arm64 container has not been requested in the meanwhile. Closing for now, but open to adding this on request.
