### ISSUE TITLE
assert()s in xattr handling functions can cause client to abort

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2896]
cvmfs_listxattr(), cvmfs_get_xattr(), GetPathForInode(), and GetDirentForInode()  contain assert()s in error pathways.
In rare production circumstances we have seen all of these assert()s trigger, resulting in a crashed fuse mount.  
(Exact root cause(s) not identified, but may be a result of a race of a lookup with repo revision update changing the entry)

Desired behaviour:
Do not assert, instead gracefully log error and propagate appropriate error back to fuse.

**Comment by mharvey-jt** [comment]
https://github.com/cvmfs/cvmfs/pull/2926

**Comment by HereThereBeDragons** [comment]
Should be fixed with #3169
