### ISSUE TITLE
hotpatch reload does not change debug mode

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2897]
A `cvmfs_config reload` does not honour any change to the CVMFS_DEBUGLOG configuration - eg a client normally running the non-debug build cannot be reloaded to  temporarily enable the debug build. 

This is an operational inconvenience as it means it is impossible to enable debugging without a complete remount.

Steps to reproduce:
1) Mount a repo using cvmfs-2.9.2, with a config file that does not have CVMFS_DEBUGLOG present
2) grep /proc/*/maps and observe libcvmfs_fuse3.so.2.9.2 in use
3) edit config file, set CVMFS_DEBUGLOG=
4) `cvmfs_config reload`
5) grep /proc/*/maps and observe libcvmfs_fuse3.so.2.9.2 is still in use, not libcvmfs_fuse3debug.so.2.9.2

Desired behaviour:
`cvmfs_config reload` loads the build of libcvmfs_fuse indicated by the current setting of CVMFS_DEBUGLOG, and not the version selected at initial mount time.

**Comment by mharvey-jt** [comment]
PR https://github.com/cvmfs/cvmfs/pull/2933

**Comment by mharvey-jt** [comment]
ref https://sft.its.cern.ch/jira/projects/CVM/issues/CVM-1745

**Comment by vvolkl** [comment]
#3227 breaks our hotpatching, we'll  need to postpone this to the next patch release.

**Comment by HereThereBeDragons** [comment]
With #3359 we should have now a correctly working version
