### ISSUE TITLE
CVMFS_IGNORE_SIGNATURE not implemented

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2899]
Per https://cvmfs.readthedocs.io/en/stable/apx-parameters.html , there is a documented configuration option `CVMFS_IGNORE_SIGNATURE`  _When set to yes, don’t verify CernVM-FS file catalog signatures_.

As of at least CVMFS 2.8 and later, this option is not implemented. Its only occurrence in the source  is in: 
```
$ grep -R IGNORE_SIG *
cvmfs/cvmfs_config:switch_list="CVMFS_IGNORE_SIGNATURE CVMFS_STRICT_MOUNT CVMFS_SHARED_CACHE \
cvmfs/server/cvmfs_server_common.sh:CVMFS_IGNORE_SIGNATURE=no
cvmfs/cvmfs_server:CVMFS_IGNORE_SIGNATURE=no
```

This is actually quite a useful option operationally, if a catalog file has to be manually manipulated outside of cvmfs.

Desired behaviour:

*) This switch is implemented as documented

**Comment by mharvey-jt** [comment]
Our quick-and-dirty implementation: https://github.com/cvmfs/cvmfs/pull/2936

**Comment by HereThereBeDragons** [comment]
PR #3317 reintroduces `_CVMFS_DEVEL_IGNORE_SIGNATURE_FAILURES`. 

This is an option that is NOT designed TO BE USED IN PRODUCTION 
(rare exceptions might exist)
