### ISSUE TITLE
expose parent catalog object via xattr

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2900]
Operationally, it can be useful to know exactly which catalog object a file or directory pertains to.
Although this information can be obtained from `cvmfs_talk cache list catalogs`, that is indirect and requires administrative access.
It would be useful to be able to obtain the catalog object for a given filesystem object by querying an extended attribute ,eg

```
attr -g catalog_hash /physical/cvmfs/repo/file
Attribute "catalog_hash" had a 40 byte value for /physical/cvmfs/repo/file:
4c107d4a53b26ab558f3186c9171bda761d92da9
```

**Comment by mharvey-jt** [comment]
Ref PR https://github.com/cvmfs/cvmfs/pull/2967

**Comment by HereThereBeDragons** [comment]
After talking with @jblomer the idea is to extend  `CatalogCountersMagicXattr` to provide the functionality of returning the hash for the respective catalog
