### ISSUE TITLE
How to update Onnx Runtime present in Centos7 setup for more execution provider support?

### ISSUE THREAD

**Issue by prikmm** [cvmfs/cvmfs#2902]
Hi,

Currently, the Onnx Runtime present in CentOS7 setup has support for default CPU provider only. Steps to reproduce:
```
[root@a257310d5595 ~]# source /cvmfs/sft.cern.ch/lcg/views/LCG_100/x86_64-centos7-gcc10-opt/setup.sh

[root@a257310d5595 ~]# python

>>> import onnxruntime as ort
>>> sess = ort.InferenceSession("resnet50/model.onnx")
2022-04-25 07:12:12.841576310 [W:onnxruntime:, graph.cc:3104 CleanUnusedInitializers] Removing initializer 'gpu_0/imagenet1k_blobs_queue_f22e83c9-22cd-4a8b-a66d-113af6b832b4_0'. It is not used by any node and should be removed from the model.
>>> sess.get_providers()
['CPUExecutionProvider']

```
I ran this in a CentoOS7 docker container:
```
docker run --privileged --cap-add SYS_ADMIN --device /dev/fuse --volume /home/$USER/Workspace/containers/cvmfs:/cvmfs:shared -e CVMFS_HTTP_PROXY=DIRECT -e CVMFS_REPOSITORIES=sft.cern.ch,geant4.cern.ch -e CVMFS_CLIENT_PROFILE=single cvmfs/service
```

I tried to find the code responsible for installing Onnx Runtime in the environment but was unsuccessful. I would like to know how to update the Onnx Runtime present to add support for more execution providers like - Intel oneDNN, Intel OpenVINO, CUDA, TensorRt etc.

Thanks!

**Comment by jblomer** [comment]
This issue tracker is for the cvmfs software itself, not for its contents. Please contact the content providers of the sft.cern.ch repository.

**Comment by prikmm** [comment]
Hi @jblomer ,

Sorry for the mistake, I just found out how to get in touch in with the repository maintainers.
