### ISSUE TITLE
optionally use vendored zlib-ng

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2917]
For performance reasons, we have replaced the vendored zlib-1.2.8 with zlib-ng, https://github.com/zlib-ng/zlib-ng
I understand there's compatibility issues when comparing compressed objects produced by different versions of zlib, which may make switching from the default undesirable under some scenarios. However, where those concerns don't apply, it would be useful to have the option to select zlib-ng at compile time.

desired behaviour:

`cmake USE_ZLIB_NG=yes` at compile time to select a vendored zlib-ng over the vendored zlib 1.2.8

**Comment by mharvey-jt** [comment]
https://github.com/cvmfs/cvmfs/pull/2934

**Comment by HereThereBeDragons** [comment]
closing as won't fix. replacement will be to support zstd
