### ISSUE TITLE
vendor libfuse

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2918]
rhel 8's libfuse3 is 3.2.1, an unhelpfully old version. In our environment we have to carry a newer build. Would it be feasible to vendor libfuse, and avoid dependency on the system dsos?

**Comment by DrDaveD** [comment]
This problem will go away in rhel-8.6 (estimated for May 2022), which is getting updated to a libfuse-3.3 version.  See bugzilla [1881557](https://bugzilla.redhat.com/show_bug.cgi?id=1881557) and [2047237](https://bugzilla.redhat.com/show_bug.cgi?id=2047237).

**Comment by mharvey-jt** [comment]
We carry 3.10.5 because of the symlink caching feature, which is significant for our use case.
https://github.com/libfuse/libfuse/releases/tag/fuse-3.10.0 (see also #2949)
