### ISSUE TITLE
Send internal affairs telemetry directly to telegraf

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2939]
For monitoring it is useful to gather and aggregate the client counters into a time series database. 
Currently this requires running a separate cron process to query, parse, and transmit the `internal affairs` data.
It would be desirable for the client to be able to communicate these directly to the local monitoring end-point, eg [telegraf](https://github.com/influxdata/telegraf).

PR #2943

**Comment by HereThereBeDragons** [comment]
Superseded by #3096
