### ISSUE TITLE
resilient retry of downloads

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2944]
In our environment we prefer that CVMFS continues to retry downloads indefinitely, only permanently failing under certain circumstances.  this allows cvmfs-using jobs to survive transient issues affecting the local proxy caches. 

The desired behaviour is:

* Order proxies based on object hash (sharding across all caches)
* Attempt download from each proxy in turn until download is successful
*  Fail (with EIO) only if:
  * a hotpatch reload occurs
  * all online proxies have returned a 404 or data that fails checksum  (behaviour: on initial error retry same proxy with `Cache-Control: no-cache` before switching proxy)
  * filesystem is unmounted

**Comment by HereThereBeDragons** [comment]
introduced by #3304
