### ISSUE TITLE
health-check for proxies

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2945]
Operationally, it is convenient if cvmfs client performs periodic health checks on proxies.  This allows:
 * proxies that need to be removed from service can be without having to take them offline
 * proxies that have failed recently can be probed and returned to use automatically
 
Behaviour:
* proxy exposes an endpoint `/healthz` which returns a 200 if the proxy is healthy. Any other response, including non-response is taken to mean the proxy is unhealthy
* cvmfs client marks as unhealthy any proxy that recently failed any object download 
* cvmfs client periodically polls `/healthz` of any proxies it has marked offline. On 200, it returns them to active state 
* cvmfs client periodically polls `/healthz` of any proxies it has marked online. On !200, it sets them as offline.
* proxy state changes are logged to counters

**Comment by HereThereBeDragons** [comment]
placeholders for those functionality are introduced by #3304 so that @mharvey-jt can use their custom code.
