### ISSUE TITLE
cache overflow when large number of open fds

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2948]
Problem: cache cleanup unlinks() cached objects, but the backing block storage is not reclaimed until any open fds are closed. This can lead to a situation where the actual size of the cache is much larger than cvmfs's account of it. In extremis, the cache can grow unboundedly, to fill all local storage, while cvmfs still believes it is within limit.

Our mitigation for this is to immediately close fds after a fuse_read() of chunked external data (which is what fills our cache).  See https://github.com/cvmfs/cvmfs/pull/2947

A more elegant solution would be for a cache cleanup event to cause the cvmfs mount process to scan through all open fds, closing those whose cache object has been unlink()ed.

**Comment by mharvey-jt** [comment]
cf https://sft.its.cern.ch/jira/projects/CVM/issues/CVM-2066

**Comment by jblomer** [comment]
Mitigated by #3263
