### ISSUE TITLE
Misleading "Transfer fuse connection to new mount...success" message

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2956]
If a cvmfs repository is unmounted but the fuse process does not go away (because something under a namespace is holding it open) then as of version 2.9 there's a message in the log file like:
```
Transfer fuse connection to new mount (via /var/lib/cvmfs/shared/fusefd.UrOfEt/sock): success
```
This happens even if the kernel is not new enough, and I think the message in that case is misleading because the mount still fails.

**Comment by jblomer** [comment]
That's true, I actually stumbled myself across that message. What it wants to say is that it managed to transfer the file descriptor from one process to another.  Whether or not that file descriptor can then be used in a call to `mount()` is a different question. The corresponding error of the `mount()` call is logged in the mount helper.
