### ISSUE TITLE
Keep catalogs compressed when in cache

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#2964]
In an environment where compute nodes have limited local storage for cvmfs cache, it would be useful if catalog files could be kept compressed when in local cache.
(We see ~3:1 compression for our catalog objects).

Possible options for this:
* https://sqlite.org/zipvfs/doc/trunk/www/index.wiki (SQLite ZIPVFS, proprietary)
* https://github.com/mlin/sqlite_zstd_vfs
* https://github.com/phiresky/sqlite-zstd

Whatever the method, for operational purposes it would be necessary retain the ability to  inspect catalogs independently of cvmfs.

(this may also be desirable for data, where that is compressed)

**Comment by HereThereBeDragons** [comment]
closing as agreed
