### ISSUE TITLE
Upgrade c-ares to 1.17.X release

### ISSUE THREAD

**Issue by koallen** [cvmfs/cvmfs#2977]
There is a bug in version 1.16.1 currently included in this repo that breaks DNS resolution of round robin names.

Basically the limit given as `naddrttls` doesn't work, the limit would get overwritten if the DNS name has more A records, and we get garbage result past the limit (or potentially memory access error). You can see more details in https://github.com/jeanpierrecartal/c-ares/commit/0d252eb3b2147179296a3bdb4ef97883c97c54d3.

https://github.com/cvmfs/cvmfs/blob/fccf0474361e23900d7f69f2786c91393c50f636/cvmfs/dns.cc#L616

I'm proposing to upgrade to 1.17 because gmock used in c-ares test got upgraded in 1.18.0 which doesn't work on GCC 4.8.5 (default in RHEL7). I've tested 1.17.2 locally and it compiles and works fine.

**Comment by jblomer** [comment]
I think we can update to version 1.18.1 right away and disable the tests. We anyway don't run them standalone but we test c-ares as part of cvmfs.
