### ISSUE TITLE
attr -g logbuffer can overflow

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2979]
When CVMFS_DEBUGLOG is enabled (at least on ligo.osgstorage.org) and presumably if there are just a lot of messages accumulated over time, then attr gets an error with the logbuffer:
```
$ attr -g logbuffer /cvmfs/ligo.osgstorage.org
attr_get: Argument list too long
Could not get "logbuffer" for /cvmfs/ligo.osgstorage.org
$ attr -l /cvmfs/ligo.osgstorage.org|grep logbuffer
Attribute "logbuffer" has a 374925 byte value for /cvmfs/ligo.osgstorage.org
```
Apparently it went over a 64kb limit.  The attribute should show a tail of some number of lines.  I think about 128 should be sufficient and still safely below a 64kb limit.

**Comment by jblomer** [comment]
Looking into it, the current implementation only shows the last 10 lines. Can you reproduce the problem?

**Comment by DrDaveD** [comment]
Yes I still get the same symptoms with cvmfs-2.10.0.  

A glance at the code doesn't look to me like it is 10 lines, but 10 calls to LogCvmfs().  The ligo.osgstorage.org debug logs have these huge long lists of x.509 DNs.  Those probably all come in one LogCvmfs() call.  I extracted one of those lists from the logs, it was 127k bytes.  If it showed up 3 times that would explain the type of size I'm seeing.

**Comment by DrDaveD** [comment]
I tried it, works for me
