### ISSUE TITLE
cvmfs client broken in Ubuntu 22.04 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by stebo85** [cvmfs/cvmfs#2984]
I installed the cvmfs client following the instructions:
```
sudo apt-get install lsb-release
wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
sudo dpkg -i cvmfs-release-latest_all.deb
sudo apt-get update
sudo apt-get install cvmfs
```

Running
```
sudo cvmfs_config setup
```

leads to
```
Error: failed to load cvmfs library, tried: './libcvmfs_fuse3_stub.so' '/usr/lib/libcvmfs_fuse3_stub.so' '/usr/lib64/libcvmfs_fuse3_stub.so' './libcvmfs_fuse_stub.so' '/usr/lib/libcvmfs_fuse_stub.so' '/usr/lib64/libcvmfs_fuse_stub.so'
./libcvmfs_fuse3_stub.so: cannot open shared object file: No such file or directory
/usr/lib/libcvmfs_fuse3_stub.so: cannot open shared object file: No such file or directory
/usr/lib64/libcvmfs_fuse3_stub.so: cannot open shared object file: No such file or directory
./libcvmfs_fuse_stub.so: cannot open shared object file: No such file or directory
libcrypto.so.1.1: cannot open shared object file: No such file or directory
/usr/lib64/libcvmfs_fuse_stub.so: cannot open shared object file: No such file or directory


Failed to read CernVM-FS configuration
```

**Comment by jblomer** [comment]
The root cause is that we unfortunately still lack 22.04 packages.  The cvmfs-release package is configured to falls back to the 18.04 packages if it doesn't know the distribution. These packages have dependencies not installed anymore in 22.04 (libssl-1.1).  A quick workaround is

```
wget https://mirror.umd.edu/ubuntu/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb
dpkg -i libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb
```

but the actual fix comes with #2886 

Let's see if we can add the platform for the upcoming 2.9.3 release.

**Comment by stebo85** [comment]
Dear @jblomer 

Thank you for the workaround - that worked perfectly :)

Thank you
Steffen

**Comment by Harshil-Jani** [comment]
> wget https://mirror.umd.edu/ubuntu/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.13_amd64.deb

Yo ! This package doesn't exist anymore. It was upgraded to libssl1.1_1.1.1f-1ubuntu2.15_amd64.deb
So, Anyone using Jammy can still use
```
wget https://mirror.umd.edu/ubuntu/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.15_amd64.deb
dpkg -i libssl1.1_1.1.1f-1ubuntu2.15_amd64.deb
```
And it works well. Thanks @jblomer

**Comment by radupopescu** [comment]
CVMFS 2.9.4, to be released shortly, comes with packages for Ubuntu 22.04: http://ecsft.cern.ch/dist/cvmfs/cvmfs-2.9.4/
