### ISSUE TITLE
cvmfs-2.9.3 el8 compilation failure

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2985]
As mentioned in [#2983](https://github.com/cvmfs/cvmfs/pull/2983#issuecomment-1154191593), the el8 build of cvmfs-2.9.3 fails on the OSG build system because pacparser tries to compile with "python" instead of "python2", and el8 has no python command.

I don't understand why the CERN compilation infrastructure didn't report a problem, but I'll propose a fix.

**Comment by radupopescu** [comment]
Getting pacparser to compile on all our targets has been painful.

**Comment by DrDaveD** [comment]
@jblomer wrote in #2983:
> The reason it builds here is the different build environment. We use this build container for EL8: https://gitlab.cern.ch/cernvm/build-images/-/blob/master/docker/centos_x86_64%3A8.Dockerfile

Ah, that will do it.  koji only pulls in packages (beyond the base ones supplied in the image) that are required by BuildRequires.   Perhaps instead of installing all those extra packages you could use yum-builddep from the yum-utils package to install just the packages required by the spec file.

**Comment by radupopescu** [comment]
Thanks, yum-builddep would be one way to go, and I agree that the current divergence between build environments is aproblem. However, this would also be a big departure from the current approach of pre-built build images. I think installing these packages in the build environment on every build will also impact the time.

Another downside, is that it introduces some asymmetry to other Linux platforms where we'd still have the pre-build images.

**Comment by DrDaveD** [comment]
Remember that I have a proposed fix in #2986.  That is exactly the patch that we have applied in the OSG build.

**Comment by jblomer** [comment]
Fixed by merging #2986
