### ISSUE TITLE
snapshot data file has doubled data

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#2991]
This is a new problem I haven't seen before.    The cvmfs-server version is 2.7.1.

The current secondary stratum 1 at IHEP is repeatedly seeing this error when attempting to snapshot from the current primary stratum 1 (they are using my cvmfs-hastratum1 scripts):
```
failed to download http://cvmfs-stratum-one-b.ihep.ac.cn:8081/cvmfs/atlas.cern.ch/stage/data/c9/ee7b96e5e472c6fab19c102449663c54f503ec (9 - host returned HTTP error)
```
That by itself isn't so unusual, but I looked into the file, and it exists on the -b machine, but it is twice the size it is supposed to be compared to the upstream stratum 1 that it read from (oasis-replica.opensciencegrid.org:8002).  In fact, the data file is 2752 bytes, exactly twice the size of 1376 bytes it is supposed to be, and I did a cmp on the data and found it was the original data repeated twice.

I found the corresponding log where it pulled the snapshot from the upstream stratum 1, and there were no anomalies printed.  It was toward the end of its run there:
```
Pulling to /srv/cvmfs/atlas.cern.ch started at Tue Jun 28 22:53:05 CST 2022 (lock 6)
...
Replicating from catalog at /repo/sw/software/0.0
  Processing chunks [46835 registered chunks]: .......................... fetched 1313 new chunks out of 26913 unique chunks
Replicating from historic catalog 6325c95bc4f44e8c9814cd97fb480de20f2eb66b
  Catalog up to date
Checking tagged snapshots...
Stopping 16 workers
Uploading manifest ensemble
Serving revision 106123
Fetched 1313 new chunks out of 32929 processed chunks

Pulling to /srv/cvmfs/lhcb-condb.cern.ch started at Tue Jun 28 22:53:31 CST 2022
```
where on the failing copy to the secondary machine it ends like this:
```
Pushing /srv/cvmfs/atlas.cern.ch started at Tue Jun 28 22:53:31 CST 2022 (lock 6)
...
Replicating from catalog at /repo/sw/software/0.0
  Processing chunks [46835 registered chunks]: .....................failed to download http://cvmfs-stratum-one-b.ihep.ac.cn:8081/cvmfs/atlas.cern.ch/stage/data/c9/ee7b96e5e472c6fab19c102449663c54f503ec (9 - host returned HTTP error)
unexpected HTTP error code 200 - please check the stratum 0 health
/usr/bin/cvmfs_server: line 7358: 65712 Aborted                 $user_shell "$(__swissknife_cmd dbg) pull -m $name         -u $stratum0                                           -w $stratum1                                           -r ${upstream}                                         -x ${spool_dir}/tmp                                    -k $public_key                                         -n $num_workers                                        -t $timeout                                            -a $retries $with_history $with_reflog                    $initial_snapshot_flag $timestamp_threshold $log_level"
Pushing /srv/cvmfs/atlas.cern.ch ended at Tue Jun 28 22:54:08 CST 2022
```

Interestingly, the timestamp on the doubled file on the -b machine was 7 minutes earlier
```
$ ls -l /storage/cvmfs/atlas.cern.ch/stage/data/c9/ee7b96e5e472c6fab19c102449663c54f503ec
-rw-r--r-- 1 root root 2752 Jun 28 22:46 /storage/cvmfs/atlas.cern.ch/stage/data/c9/ee7b96e5e472c6fab19c102449663c54f503ec
```
so it was likely initially downloaded during a previous snapshot.   stat shows more specifically the modification time was 22:46:13.

Aha!  Searching back in the pull log for atlas.cern.ch I indeed found an error at that timestamp at around that point:
```
Replicating from catalog at /repo/sw/software/0.0
  Processing chunks [46835 registered chunks]: .....................failed to download http://cvmfs-stratum-zero.cern.ch:8000/cvmfs/atlas.cern.ch/data/9a/bf93e966a9a0c20f4a78830ae8f86ed3438357 (15 - host serving data too slowly)
couldn't reach Stratum 0 - please check the network connection
/usr/bin/cvmfs_server: line 7358: 80240 Aborted                 $user_shell "$(_
_swissknife_cmd dbg) pull -m $name         -u $stratum0
                  -w $stratum1                                           -r ${up
stream}                                         -x ${spool_dir}/tmp
                       -k $public_key                                         -n
 $num_workers                                        -t $timeout
                            -a $retries $with_history $with_reflog
      $initial_snapshot_flag $timestamp_threshold $log_level"
ERROR from cvmfs_server, skipping push!

Pulling to /srv/cvmfs/researchinschools.egi.eu started at Tue Jun 28 22:46:13 CST 2022 (lock 3)
```
That's not the same file, but snapshot does multiple parallel files so perhaps it was in the middle of doing that other file, it had just finished writing the file, caught a signal, and wrote it out again.  Or something like that.

**Comment by jblomer** [comment]
The line `unexpected HTTP error code 200` is very interesting. I can't quite see how cvmfs would set an HTTP error condition after having received `200 OK`.

In any case, updating to the latest cvmfs version is probably a good idea.

**Comment by DrDaveD** [comment]
We had another case of this with cvmfs-server-2.9.3 on the machine oasis-replica.opensciencegrid.org in the lhcb.cern.ch repo.  The snapshot error on the snapshotting stratum 1 (in swinburne) looked the same:
```
failed to download [http://oasis-replica.opensciencegrid.org:8002/cvmfs/lhcb.cern.ch/data/34/e7fdf61dfddefd44889b3aba6134e3726d91a6](https://urldefense.proofpoint.com/v2/url?u=http-3A__oasis-2Dreplica.opensciencegrid.org-3A8002_cvmfs_lhcb.cern.ch_data_34_e7fdf61dfddefd44889b3aba6134e3726d91a6&d=DwQF-g&c=gRgGjJ3BkIsb5y6s49QqsA&r=GuA-VxQ15hY8L8QSEMSiQA&m=VLDyzV07dP7mBiHPtIYNtEYfsbYFlR5MoF6PpfbKBe5pqdMEEGJpfvd9eCr-V9FH&s=dQ47c57XMDjjWhgsCjl7hMNECR2WeoYRxAHau26neNY&e=) (9 - host returned HTTP error)

unexpected HTTP error code 200 - please check the stratum 0 health
```
When run with CVMFS_SERVER_DEBUG=3 the snapshotting stratum 1 saw 
```
(download) hash verification of [http://oasis-replica.opensciencegrid.org:8002/cvmfs/lhcb.cern.ch/data/34/e7fdf61dfddefd44889b3aba6134e3726d91a6](https://urldefense.proofpoint.com/v2/url?u=http-3A__oasis-2Dreplica.opensciencegrid.org-3A8002_cvmfs_lhcb.cern.ch_data_34_e7fdf61dfddefd44889b3aba6134e3726d91a6&d=DwQF-g&c=gRgGjJ3BkIsb5y6s49QqsA&r=GuA-VxQ15hY8L8QSEMSiQA&m=VLDyzV07dP7mBiHPtIYNtEYfsbYFlR5MoF6PpfbKBe5pqdMEEGJpfvd9eCr-V9FH&s=dQ47c57XMDjjWhgsCjl7hMNECR2WeoYRxAHau26neNY&e=) failed (expected 34e7fdf61dfddefd44889b3aba6134e3726d91a6, got 22ab75202098c75e02ba3de3325ed33d8661f444)    [10-19-2022 10:37:30 AEDT]
```
There was indeed a swissknife crash at the same timestamp that was on the file, again on a different file:
```
........failed to download http://cvmfs-stratum-zero.cern.ch:8000/cvmfs/lhcb.cern.ch/data/21/da53d5fba22ca5913eb0fc00003468625f5e57 (15 - host serving data too slowly)
couldn't reach Stratum 0 - please check the network connection
PANIC: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc7/build/BUILD/cvmfs-2.9.3/cvmfs/swissknife_pull.cc : 286
Download error
/usr/bin/cvmfs_server: line 7471: 11677 Aborted                 $user_shell "$(__swissknife_cmd dbg) pull -m $name         -u $stratum0                  -w $stratum1                                           -r ${upstream}                                         -x ${spool_dir}/tmp                       -k $public_key                                         -n $num_workers                                        -t $timeout                            -a $retries $with_history $with_reflog      $initial_snapshot_flag $timestamp_threshold $log_level"
ERROR from cvmfs_server snapshot!
Finished lhcb.cern.ch at Wed Oct 12 22:24:53 CDT 2022
```
The disturbing thing is that there "host serving data too slowly" errors is not uncommon; there were 15 cases on that repo alone in last week's log.

**Comment by jblomer** [comment]
Can you check if you see in the syslog the message `data corruption with no-cache header, try another host`.

**Comment by jblomer** [comment]
I can't quite pinpoint it but I can imagine that the problem is in [resetting the C file stream in the download manager](https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/download.cc#L1415).  We flush, truncate, and then rewind. We may want to rewind before truncating, and we should use `fseek` so that we can check the return value.

**Comment by DrDaveD** [comment]
> Can you check if you see in the syslog the message `data corruption with no-cache header, try another host`.

No, I don't see that.  I see only
> Oct 12 22:24:53 hcc-cvmfs2.unl.edu cvmfs_server: (lhcb.cern.ch) failed to snapshot from http://cvmfs-stratum-zero.cern.ch:8000/cvmfs/lhcb.cern.ch

**Comment by DrDaveD** [comment]
There was another case on the secondary IHEP stratum 1 reading from its primary, just like the original report in this issue, at local time Oct 27 11:39.  This time however, it wasn't the entire file that was duplicated, it was just the portion after the first 4096 bytes.  The good file was 5128 bytes long, and the bad file had an additional (5128-4096)=1032 bytes appended which were identical to the previous 1032 bytes, for a total of 6160 bytes. The repository was lhcb.cern.ch, and the cvmfs-server version was 2.7.1.

**Comment by DrDaveD** [comment]
There was another case of this last evening on the main Nebraska OSG stratum 1, running cvmfs-server-2.9.3, in repository des.opensciencegrid.org.  The good file was 217 bytes long and the bad file 434 bytes long.  There was a failure during the minute it was created:
```
failed to download http://oasiscfs.fnal.gov:8000/cvmfs/des.opensciencegrid.org/data/4d/180c45f32c66eedb53201f0db4ae5c1a62bf08 (9 - host returned HTTP error)
unexpected HTTP error code 503 - please check the stratum 0 health
PANIC: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc7/build/BUILD/cvmfs-2.9.3/cvmfs/swissknife_pull.cc : 286
Download error
/usr/bin/cvmfs_server: line 7471: 22795 Aborted                 $user_shell "$(__swissknife_cmd dbg) pull -m $name         -u $stratum0
                  -w $stratum1                                           -r ${upstream}                                         -x ${spool_dir}/tmp
                       -k $public_key                                         -n
 $num_workers                                        -t $timeout
                            -a $retries $with_history $with_reflog
      $initial_snapshot_flag $timestamp_threshold $log_level"
ERROR from cvmfs_server snapshot!
Finished des.opensciencegrid.org at Tue Dec 27 19:24:04 CST 2022
```
and there was apparently a networking problem because no updates got through until 61 minutes later.

**Comment by jblomer** [comment]
I backported #3085 to 2.10.1. Let's hope it fixes the problem.

**Comment by DrDaveD** [comment]
Two more corrupted files were discovered on the main Nebraska OSG stratum 1 again today.  It has not yet been upgraded to 2.10.1, although the backup stratum 1 there has.  In this case one of them was the usual duplicated data, and the other was a case like one that was reported just once here before, where the first 4096 bytes was a duplicate, followed by the entire contents of the original 4827-byte file.

**Comment by DrDaveD** [comment]
I haven't seen this bug occur again since 2.10.1, so I'm closing this issue.
