### ISSUE TITLE
cvmrepo is sporadically down

### ISSUE THREAD

**Issue by stebo85** [cvmfs/cvmfs#2993]
Dear CVFMS team,

We install CVMFS in ubuntu on our Github Actions CI to test our CVMFS deployments and sporadically (mulitple times per month over the last year) the CI fails and we get errors when installing the cvmfs package for debian:

Err:22 https://cvmrepo.web.cern.ch/cvmrepo/apt focal-prod InRelease
  403  Forbidden [IP: 137.138.31.235 443]
Reading package lists...
E: Failed to fetch http://cvmrepo.web.cern.ch/cvmrepo/apt/dists/focal-prod/InRelease  403  Forbidden [IP: 137.138.31.235 443]
E: The repository 'http://cvmrepo.web.cern.ch/cvmrepo/apt focal-prod InRelease' is not signed.
[DEBUG]: apt-get install cvmfs
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cvmfs

It looks like the server is sporadically offline and I was wondering if this is a known problem? Is this related to github accessing the server or are other users seeing this as well?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/4021595/176977700-80502ed5-4aed-43c2-9d78-534953069104.png">

**Comment by SamLMB** [comment]
While attempting to update the package list, I receive the following error which may be related:
```
Get:6 https://cvmrepo.web.cern.ch/cvmrepo/apt bullseye-prod Release.gpg [198 B]
Err:6 https://cvmrepo.web.cern.ch/cvmrepo/apt bullseye-prod Release.gpg
  The following signatures were invalid: BADSIG 230D389D8AE45CE7 CernVM Administrator (cvmadmin) <cernvm.administrator@cern.ch>
```
and further down at the end of `apt update`
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cvmrepo.web.cern.ch/cvmrepo/apt bullseye-prod Release: The following signatures were invalid: BADSIG 230D389D8AE45CE7 CernVM Administrator (cvmadmin) <cernvm.administrator@cern.ch>
W: Failed to fetch http://cvmrepo.web.cern.ch/cvmrepo/apt/dists/bullseye-prod/Release.gpg  The following signatures were invalid: BADSIG 230D389D8AE45CE7 CernVM Administrator (cvmadmin) <cernvm.administrator@cern.ch>
```
I am running cvmfs on a Debian 11.3 system.

**Comment by jblomer** [comment]
I think these are two different errors. @SamLMB I'm trying to understand what's breaking the signature. Should have more info shortly.

@stebo85 The occasional web server glitches have, unfortunately, been a problem for a long time with the service that hosts these packages.  I'll try storing them on the CERN S3 service, which should be more stable.  A new `cvmfs-release` binary will then have the updated repository URL. Also here, more info shortly.

**Comment by jblomer** [comment]
@SamLMB The signature issue should be solved; in the course of releasing a new patch version, we had a temporarily inconsistent repository state online, sorry about that!

**Comment by jblomer** [comment]
@stebo85 The new [cvmfs-release package](https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release_4.0-1_all.deb) uses the S3 backed mirror (and provides access to the Ubuntu 22.04 repositories). Please let me know if that works for you.  I'll then point the cvmfs-release-latest package to this new version.

**Comment by stebo85** [comment]
Dear @jblomer,

That works beautifully so far :) Thank you so much for fixing this issue.

Thank you
Steffen

**Comment by jblomer** [comment]
Thanks for confirming!  I realized that the new S3 endpoint is not reachable by HTTPS due to certificate issues.  I'll need to release another cvmfs-release package with an updated URL (`cvmrepo.s3.cern.ch` instead of `cvmrepo.web.cern.ch.s3.cern.ch`). I'll do that on Monday.

**Comment by jblomer** [comment]
I updated the `cvmfs-release-latest` symlink to version 4.1 of the package.  This version uses the new `cvmrepo.s3.cern.ch` endpoint.  Please let me know once you're switched, as I'd then like to invalidate the 4.0 package.

**Comment by stebo85** [comment]
I switched to cvmfs-release-latest, so old 4.0 package can be disabled :)
