### ISSUE TITLE
cvmfs_statfs() slow

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3015]
The Pycharm IDE likes to index filesystems. Its behaviour when parallel walking the filesystem is --  for no obvious reason -- to call statfs() + stat() on every entity. It turns out that cvmfs_statfs() is a rather slow operation, and as a result we see cvmfs2 consuming very large amounts of cpu. This causes the latency for other cvmfs filesystem operations to spike

This is arguably incorrect behaviour by Pycharm, but it has revealed a slow path in cvmfs. It seems that cvmfs_statfs() should be quite a quick operation, so perhaps this path could be optimised.

for reference, this is logged with Pycharm as bug https://intellij-support.jetbrains.com/hc/en-us/requests/4214503 and affects at least Pycharm 2022.1 Professional Edition

**Comment by jblomer** [comment]
The time is spent in returning the space and number of files in the cache.  This can of course be cached for a while at the cost of potentially slightly outdated information. It may be a useful protection against rogue applications and monitoring scripts.
