### ISSUE TITLE
Wrong conditions for retry manifest download?

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3032]
In function Fetch the `if`-statement should most likely be `(result == kFailLoad)`?

https://github.com/cvmfs/cvmfs/blob/186cbd51f563daa5f0ac574d000f666cf6468872/cvmfs/manifest_fetch.cc#L198-L199

**Comment by jblomer** [comment]
Looking at the method documentation, the condition is in fact correct. The point is to trigger a host switch even if download the whitelist was successful but the whitelist is corrupt/outdated.  I'll close this one.
