### ISSUE TITLE
Expose object metadata via extended attribute

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3034]
It would be useful to expose the object store metadata for an external object via an extended attribute. Querying this xattr would cause CVMFS to issue a HEAD for the object and return all associated headers.
(This should be a protected xattr available only to privileged users)

**Comment by HereThereBeDragons** [comment]
hi @mharvey-jt 
is the exposure of external_url ( #3101 ) enough for you to acquire the metadata?
if there are no strong arguments for the direct exposure of the metadata via cvmfs we would consider it a bit out of scope of cvmfs

**Comment by mharvey-jt** [comment]
Yep, we don't really need this as a CVMS feature.
