### ISSUE TITLE
`make install` brakes link when copying libcvmfs_fuse3* to /usr/lib

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3035]
When using a local (non-system) fuse3 installation, one can set in the configuration to use fuse3 (see below *installation process*). While in the `build` directory afterwards the `libcvmfs_fuse3*` have all the correct linking included, when using `sudo ninja install` the copied `libcvmfs_fuse3*` in `/usr/lib` have a broken link for `libfuse3.so`:

e.g.
```
~/cvmfs/build/cvmfs $ ldd libcvmfs_fuse3.so
	linux-vdso.so.1 (0x00007fff7c37c000)
	libfuse3.so.3 => /usr/local/lib/x86_64-linux-gnu/libfuse3.so.3 (0x00007f2de7e7f000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2de7dcb000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f2de7af5000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f2de7aec000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2de7ac9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2de7ac3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2de78df000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2de7790000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2de7775000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2de7583000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2de821d000)
```
but 
```
/usr/lib $ ldd libcvmfs_fuse3.so
	linux-vdso.so.1 (0x00007ffc83d4b000)
	libfuse3.so.3 => not found
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f7109804000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f710952e000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f7109525000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7109502000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f71094fc000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7109318000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f71091c9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f71091ae000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7108fbc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7109c17000)
```

Setup:
- `~/cvmfs/build` is empty
- all `libcvmfs*` in `/usr/lib/`  are deleted

Installation process (inside `~/cvmfs/build`):
```
export FUSE3_INCLUDE_DIR_PATH=/usr/local/include/
export FUSE3_LIBRARY=/usr/local/lib/x86_64-linux-gnu/libfuse3.so.3.10.5
cmake -G Ninja -D BUILD_UNITTESTS=ON -D BUILD_GATEWAY=ON -D FUSE3_INCLUDE_DIR=$FUSE3_INCLUDE_DIR_PATH -D FUSE3_LIBRARY=$FUSE3_LIBRARY ../

ninja 
sudo ninja install
```

Current workaround:
- Manually copy `libcvmfs_fuse3*` from `~/cvmfs/build/cvmfs/` to `/usr/lib` or `/usr/lib64`
  ` sudo cp -a libcvmfs_fuse3* /usr/lib64/`
- fix access right for `libcvmfs_fuse3*.so.*`
  `chmod -x libcvmfs_fuse3*.so.*` 

Correct fuse3 access can be tested with:
```
export CVMFS_REPO=my.test.repo
sudo /usr/bin/cvmfs2 -d -f -o rw,system_mount,fsname=cvmfs2,allow_other,grab_mountpoint,uid=998,gid=997,libfuse=3 $CVMFS_REPO /mnt/test
```

If it is not working, following error is visible when trying to mount with fuse3:
```
Debug: enforcing libfuse version 3
Error: failed to load cvmfs library, tried: './libcvmfs_fuse3_stub.so' '/usr/lib/libcvmfs_fuse3_stub.so' '/usr/lib64/libcvmfs_fuse3_stub.so'
./libcvmfs_fuse3_stub.so: cannot open shared object file: No such file or directory
libfuse3.so.3: cannot open shared object file: No such file or directory
/usr/lib64/libcvmfs_fuse3_stub.so: cannot open shared object file: No such file or directory
```
  
Tested on: Ubuntu 20.04 LTS
Only tested with `ninja` not with `cmake`

**Comment by HereThereBeDragons** [comment]
After some research and finding [this (comment of atomicules)](https://stackoverflow.com/questions/7970544/cmake-make-install-output-cant-find-shared-qt-libraries-under-redhat)* the underlying prolbme is that `make install` strips `rpath` by default to use default system libs. So this needs to be deactivated.

Solution is adding `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON` to `cmake`
or `SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)`

new command would be then
```
cmake -G Ninja -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON  -D BUILD_UNITTESTS=ON -D BUILD_GATEWAY=ON -D FUSE3_INCLUDE_DIR=$FUSE3_INCLUDE_DIR_PATH -D FUSE3_LIBRARY=$FUSE3_LIBRARY_PATH ../
```

I verified it by making a clean install.

@jblomer  *Not sure what cvmfs wants as default?*

**Comment by jblomer** [comment]
I think we should leave the default as is but document this cmake option under [Building from sources](https://cvmfs.readthedocs.io/en/stable/cpt-quickstart.html#building-from-source)
