### ISSUE TITLE
Cached symlink retains old version when `readlink` is called immediatly after catalog reload

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3036]
Problem: Cached symlinks retain old values when the catalog is reloaded by the automatic catalog reload or `cvmfs_talk remount` (without `sync`). New version is only loaded when the cache is automatically evicted.

Reason:
`LoadCatalog` requires as last step `fuse_remounter_->TryFinish();` which is called in `cvmfs_lookup`, `cvmfs_getattr`, and `cvmfs_opendir` but NOT in `cvmfs_readlink`

Possible solutions:
- LoadCatalog applies `fuse_remounter_->TryFinish();` 
OR
- Add `fuse_remounter_->TryFinish();` to `cvmfs_readlink`

**Comment by jblomer** [comment]
I guess this issue is fixed as a side-effect of #2949?

**Comment by HereThereBeDragons** [comment]
Yes should be. This was a problem of not expiring the dentries
