### ISSUE TITLE
Cleanup in cvmfs parameters documentation

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3038]
Here: https://cvmfs.readthedocs.io/en/stable/apx-parameters.html
or https://github.com/cvmfs/doc-cvmfs/blob/latest/apx-parameters.rst

Units are missing, e.g. for:
-  `CVMFS_KCACHE_TIMEOUT` -- should be seconds?
- `CVMFS_LOW_SPEED_LIMIT` -- bytes? mb/s??

- `CVMFS_IGNORE_XDIR_HARDLINKS`  and `CVMFS_GENERATE_LEGACY_BULK_CHUNKS` still needed?
- What are special files refered in `CVMFS_IGNORE_SPECIAL_FILES`?

Possible typos in description/ latex remnants:
- `CVMFS_SYSTEMD_NOKILL`
- `CVMFS_USYSLOG`
- `CVMFS_GARBAGE_COLLECTION`
- `CVMFS_SYSLOG_FACILITY`
- `CVMFS_SERVER_URL`
- 

- Everywhere but `CVMFS_BACKOFF_INIT` it starts with `xx in seconds` and not `seconds for xxx`

- Would it be useful to rename `CVMFS_MAX_TTL` to `CVMFS_MAX_CATALOG_TTL`?

- If possible it would also be good if the table can be wider or automatic line break, because right now its impossible  to read everything without sideways scrolling

**Comment by jblomer** [comment]
- `CVMFS_KCACHE_TIMEOUT`: seconds
- `CVMFS_LOW_SPEED_LIMIT`: byte / second
- For `CVMFS_GENERATE_LEGACY_BULK_CHUNKS` and `CVMFS_IGNORE_XDIR_HARDLINKS`: lets add a new section "deprecated options, to be removed in future versions"
- Special files are pipes, sockets, block device and character device files; could be spelled out somewhere.
- `CVMFS_MAX_TTL` vs. `CVMFS_MAX_CATALOG_TTL`: I think it's not worth the effort (to be backwards compatible, at the end we'd need to check two options)

And: fully agree on the line breaks! One would need to figure out how that works in reST markup.
