### ISSUE TITLE
Garbage collection fails when using `-a` and `-L` flags together and repos are owned by different users

### ISSUE THREAD

**Issue by natefoo** [cvmfs/cvmfs#3045]
The failure occurs when attempting to open the log file, which appears to happen as the repo owner:

```console
[root@cvmfs0-psu0 ~]# cvmfs_server gc -a -L /var/log/cvmfs/gc.log
YOU ARE ABOUT TO DELETE DATA! Are you sure you want to do the following:
Affected Repositories:         sandbox.galaxyproject.org refgenomes-databio.galaxyproject.org data.galaxyproject.org cvmfs-config.galaxyproject.org
Dry Run (no actual deletion):  no
Needs Reflog reconstruction:   no
Preserve Revisions newer than: 08/29/22 18:38:54

Please confirm this action (y/N)? y
```

In the log file, you get the following. The `cvmfs-config` repo is owned by root and succeeds, but the rest are owned by unprivileged users and fail:

```
Starting sandbox.galaxyproject.org at Thu Sep  1 18:39:00 UTC 2022
Running Garbage Collection
failed to open deletion log file (errno: 13)
Fail (6)!
ERROR from cvmfs_server gc!
Finished sandbox.galaxyproject.org at Thu Sep  1 18:39:01 UTC 2022

Starting refgenomes-databio.galaxyproject.org at Thu Sep  1 18:39:01 UTC 2022
Running Garbage Collection
failed to open deletion log file (errno: 13)
Fail (6)!
ERROR from cvmfs_server gc!
Finished refgenomes-databio.galaxyproject.org at Thu Sep  1 18:39:02 UTC 2022

Starting data.galaxyproject.org at Thu Sep  1 18:39:02 UTC 2022
Running Garbage Collection
failed to open deletion log file (errno: 13)
Fail (6)!
ERROR from cvmfs_server gc!
Finished data.galaxyproject.org at Thu Sep  1 18:39:03 UTC 2022

Starting cvmfs-config.galaxyproject.org at Thu Sep  1 18:39:03 UTC 2022
Running Garbage Collection
  --> marking unreferenced objects [Thu, 01 Sep 2022 18:39:03 GMT]
  --> sweeping unreferenced objects [Thu, 01 Sep 2022 18:39:03 GMT]
  --> done garbage collecting [Thu, 01 Sep 2022 18:39:03 GMT]
# Garbage Collection started at 1 Sep 2022 18:39:03
# Garbage Collection finished at 1 Sep 2022 18:39:03

Statistics stored at: /var/spool/cvmfs/cvmfs-config.galaxyproject.org/stats.db
Finished cvmfs-config.galaxyproject.org at Thu Sep  1 18:39:04 UTC 2022
```

If you leave off the `-L` option, the log file can be written to (just one successful example is shown), but of course you can't control the log file path in that case:

```
Starting sandbox.galaxyproject.org at Thu Sep  1 18:32:47 UTC 2022
Running Garbage Collection
  --> marking unreferenced objects [Thu, 01 Sep 2022 18:32:48 GMT]
  --> sweeping unreferenced objects [Thu, 01 Sep 2022 18:32:51 GMT]
  --> done garbage collecting [Thu, 01 Sep 2022 18:32:51 GMT]
Statistics stored at: /var/spool/cvmfs/sandbox.galaxyproject.org/stats.db
Finished sandbox.galaxyproject.org at Thu Sep  1 18:32:52 UTC 2022
```

Tested with 2.9.4 on CentOS 7.

**Comment by jblomer** [comment]
@DrDaveD Do you have a suggestion how we should handle this case?

**Comment by DrDaveD** [comment]
These are stratum zero, publishing repositories, not replicas?  Does it also fail if you run cvmfs_server gc individually?

I don't think I tested gc -a on stratum 0.  Although it seems it ought to be able to work, generally running gc on publishing repositories needs to be coordinated with the person who maintains it because gc interferes with publishing.  It's generally better to let the maintainer control when it runs than for a system administrator to run it at an arbitrary time.

I have recommended to the Fermilab publishing machine administrator to not run gc for the maintainers but to instead install [cvmfs-servermon](https://github.com/cvmfs-contrib/cvmfs-servermon) and probe it daily to verify that the maintainers are running gc on collectable repositories regularly, and to bug them if they don't run it.

**Comment by natefoo** [comment]
> These are stratum zero, publishing repositories, not replicas? 

Correct

> Does it also fail if you run cvmfs_server gc individually?

It would appear so:

```
[root@cvmfs0-psu0 ~]# cvmfs_server gc -L /var/log/cvmfs/gc.log data.galaxyproject.org
YOU ARE ABOUT TO DELETE DATA! Are you sure you want to do the following:
Affected Repositories:         data.galaxyproject.org 
Dry Run (no actual deletion):  no
Needs Reflog reconstruction:   no
Preserve Revisions newer than: 09/04/22 15:36:24

Please confirm this action (y/N)? y
Running Garbage Collection 
failed to open deletion log file (errno: 13)
Fail (6)!
```

Thanks for the tip - we can certainly switch to a less automated gc process on release managers if that's recommended. In the case of many of our repos, though, the publishing is also automated. We could also gc on publish, I forget why we initially switched to disabling auto gc (perhaps for increased publish speed).

**Comment by jblomer** [comment]
@natefoo Is it correct that you eventually worked around this issue? Should we continue keeping it open?

**Comment by natefoo** [comment]
Yes, I simply don't set `-L`, which works for my case, although the issue still exists. If you want to close this, that's fine.
