### ISSUE TITLE
recovering a repository with a lost tag database object

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3049]
Hi,

We have a repository that has somehow lost its tags database object (the object indicated with `H` in the `.cvmfspublished` file). Althrough it is still mountable, it is no longer possible to publish to it. `cvmfs_server publish` gives the error `cannot load tag database`.
Accepting that the tags, which we weren't using anyway, are lost, do you have advice on how to recover from this situation, restoring the repo to a point at which we can continue to publish from the current state?

The error is arising at https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/publish/repository.cc#L187-L202 -  It seems like this could be fixed by resetting the history with `manifest_->set_history(NULL)` before this block, causing the creation of a new history at https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/publish/repository.cc#L205 . Would that be sufficient?

**Comment by jblomer** [comment]
I think that's correct (although we have never been in this situation).

I'd test the approach with a minimal test repository first. After the new tag database is published, you can check if the repository is mountable, if you can continue to publish changes and if a full `cvmfs_server check` returns no problems.

**Comment by jblomer** [comment]
(As a follow-up, it would be useful to have a utility that installs a minimal working manifest if the current one gets corrupted.)

**Comment by mharvey-jt** [comment]
Would replacing the manifest with an appropriately-signed one omitting the `H` entry also be sufficient?

**Comment by jblomer** [comment]
Yes, that should have the same effect.

**Comment by mharvey-jt** [comment]
thanks @jblomer . For posterity, it was also necessary to patch  `InitializeEnvironment()` in `cvmfs/swissknife_history.cc` to initialize a new history database if the download failed.

```
if( !env->history) {
    fprintf(stderr, "FAILED TO DOWNLOAD HISTORY OBJECT\n");
    env->history = history::SqliteHistory::Create( env->history_path.path(),  env->manifest->repository_name() );
  }
  ```
