### ISSUE TITLE
cpplint fails silently when called with python3

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3050]
Would be good to either add support for python3 or that at least some output comes that python3 is not supported.

Running with python3 gives currently no output, giving a false perception that a file is ok (if you dont know that cpplint should *always* give some form of output)

**Comment by jblomer** [comment]
That should be fixed by [moving to clang-format](https://sft.its.cern.ch/jira/browse/CVM-2030). For the moment, patching the `cpplint` utility to return with an error in this case would be an improvement.

**Comment by jblomer** [comment]
Fixed by #3322
