### ISSUE TITLE
Investigate fuse-t as possible alternative for cvmfs on macOS

### ISSUE THREAD

**Issue by jblomer** [cvmfs/cvmfs#3052]
The [fuse-t](https://www.fuse-t.org/) library promises to be a drop-in replacement for osxfuse. It should work purely in user-space (no kernel extension). We should try it out with the cvmfs tests.

**Comment by vvolkl** [comment]
Fuse-t is now also mentioned in the libfuse docs: https://github.com/libfuse/libfuse/commit/6bda4091d4cc67e8f24cd7cb8dc93d076e115e27

**Comment by vvolkl** [comment]
Done with #3587
