### ISSUE TITLE
EIO from kfuse readdir() when cache_readdir=1 set in reply to fuse_opendir()

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3054]
Hi,

Just a note that we are seeing EIOs from rhel8.x kfuse (8.3, 8.5 tested) in relation to readdir caching. Steps to reproduce:
* set up a repo with some directory hierarchy
* mount with CVMFS_AUTO_UPDATE=no to ensure no catalog switching / cache invalidation is happening
* on a client start a dozen instances of `find /cvmfs/XXX -type -d -exec ls -l {} \; > /dev/null 2>&1 &`
* observe occasional EIOs correlated with the switch to new repo versions.
* observe WARNs in the dmesg

The proximal source of the EIO is `readdir.c:396`, in `fuse_parse_cache()`: 
```
(gdb) l *fuse_readdir+0x5bb
0x1126b is in fuse_readdir (fs/fuse/readdir.c:396).
391			if (nbytes < FUSE_NAME_OFFSET || !dirent->namelen)
392				break;
393	
394			reclen = FUSE_DIRENT_SIZE(dirent); /* derefs ->namelen */
395	
396			if (WARN_ON(dirent->namelen > FUSE_NAME_MAX))
397				return FOUND_ERR;
398			if (WARN_ON(reclen > nbytes))
399				return FOUND_ERR;
400			if (WARN_ON(memchr(dirent->name, '/', dirent->namelen) != NULL))
```
we have a ticket open with RedHat about this.

Retrying with https://github.com/cvmfs/cvmfs/blob/04fb3e3ddec7642b82da60f0d0603232bbcb6950/cvmfs/cvmfs.cc#L927
patched out, the problem can't be reproduced.

**Comment by jblomer** [comment]
Thanks for letting us know!  If you can share it, I'd be interested to join the the watch list of the bugzilla ticket.

**Comment by jblomer** [comment]
@mharvey-jt If I remember correctly, this has been patched by RH. I'll therefore close this, please feel free to reopen if necessary.
