### ISSUE TITLE
Counter should not accept a non-number and instead explicitly fail with a ValueError

### ISSUE THREAD

**Issue by rbanffy** [cvmfs/cvmfs#3058]
In https://github.com/cvmfs/cvmfs/blob/devel/python/parser.py, the `__init__` method takes a "number" parameter that, when the `int` function can't convert it to an integer, the function silently accepts it and converts to a zero. This masks invalid calls to the function.

**Comment by jblomer** [comment]
Thanks for the issue! The python scripts are for internal use only and also not part of the official source tarball. So may not get to that anytime soon.

**Comment by rbanffy** [comment]
Mind if I try my hand at it?

**Comment by jblomer** [comment]
Sure, please go ahead.

**Comment by jblomer** [comment]
Closing this for the time being. Please feel free to reopen if you are still planning to work on that.
