### ISSUE TITLE
Add HTTPS support for connecting to gateway

### ISSUE THREAD

**Issue by nicolamori** [cvmfs/cvmfs#3060]
As stated in [this forum post](https://cernvm-forum.cern.ch/t/ca-certificates-for-cvmfs-server-on-publisher-machine/224/2) it is not currently possible to connect to a gateway from a publisher using HTTPS. This use case has potential use cases (e.g. on-demand publishers on a cloud infrastructure that interact with a gateway hosted on another cloud) so please add support.
Thanks.

**Comment by jblomer** [comment]
I think the relevant code is in repository_session.cc (`MakeAcquireRequest`, `MakeDropRequest`). My guess it that you can use the `SslCertificateStore` class (ssl.[h,cc]) in order to set the system certificate path to the CURL handle.

**Comment by nicolamori** [comment]
I will try to modify the code as soon as I have some time to set up a dev environment. At the moment I'm using http for my test bed but I will need https for production so at a certain point I'll tackle this. Thanks for the guidance.

**Comment by nicolamori** [comment]
@jblomer I have been able to put together something that seems to work. Please revise it carefully since I'm not an expert at all of libcurl. Thank you.
