### ISSUE TITLE
cvmfs_server ingest issue with file ownership

### ISSUE THREAD

**Issue by maarten-litmaath** [cvmfs/cvmfs#3073]
To publish a tar ball in CVMFS, one can use a command like this:

cvmfs_server ingest --tar_file ... --base_dir ... repository_name

As that command effectively runs with privileges, it will _preserve_ the ownership of the files and directories as recorded in the tar ball, somewhat contrary to expectations and undocumented:

https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#tarball-publishing

That documentation includes the following statement:

Note that currently the [.cvmfsdirtab file](https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#sct-dirtab) does not apply to the ingest command.

It does not _warn_ the user, however, that when the repository makes use of a "dirtab", the ingest command _must_ be run with the "-c" / "--catalog" option to avoid the following problem on the next publication of anything:

$ cvmfs_server publish ...
Using auto tag 'generic-2022-09-27T08:18:22Z'
Failed to create nested catalog marker at '/cvmfs/.../.cvmfscatalog' (errno: 13)
Failed to apply .cvmfsdirtab

The nested catalog could not be created due to its directory not being owned by the repository owner...  :-(

(CERN SNow ticket RQF2133247 has the details about how that case was resolved with help from the experts.)

IMO, the ingest command should by default ensure all files and directories extracted from the tar ball end up owned by the repository owner in CVMFS.  A "--preserve" option could allow the user to specify that the ownership should be preserved as recorded in the tar ball.

A second potential issue concerns the failed publication: does the command have to insist on _all_ catalogs being creatable?  Is it not possible just to do the ones that are allowed and warn about the ones that failed?

There appears to be an inconsistency in the cvmfs_server command behavior: for "ingest" it essentially runs as superuser, while for "publish" it does not...

**Comment by jblomer** [comment]
Let's clarify the documentation first.

Overwriting the uid/gid with the repository owner one makes sense, I'm not sure yet what should be the default though.  The dirtab handling is a separate issue. I think it makes sense if `ingest` checks the dirtab and warns on conflict.

**Comment by iraklic** [comment]
Hello,

Has there been any action taken to make `injest` work without issues related to retaining the ownership and thus causing the conflicts? I checked the documentation as well, and unless I am looking at the old version I believe no clarification been added.

Thanks,
Irakli

**Comment by vvolkl** [comment]
Fixed by #3362
