### ISSUE TITLE
`cvmfs_talk` does not warn if `-i repo` is needed but not given

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3075]
Commands in `cvmfs_talk` that need `-i repo` finish without any output. This creates confusion if the execution was successful or not. 

It would be better if `cvmfs_talk` gives feedback that arguments are missing.

**Comment by DrDaveD** [comment]
Do you mean for example if someone does `cvmfs_talk -i cms.cern.ch` it simply says `Command missing` without giving help?  I have always found that to be annoying.  That happens even without a `-i` option.

**Comment by DrDaveD** [comment]
Oh, no, I see you're talking about something like `cvmfs_talk host info` when no `-i` is given.  It actually will do something if `CVMFS_REPOSITORIES` is set, but that can be quite confusing too if those repositories aren't mounted at the time.

**Comment by HereThereBeDragons** [comment]
The commands i stumbled across were `cvmfs_talk tracebuffer flush` and `cvmfs_talk remount sync`.

So I guess multiple subcommands but not all will have this issue. Also some commands can take `-p` instead of `-i`
