### ISSUE TITLE
cvmfs_talk reload may cause client to revert to earlier revision

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3080]
As a result of some race between http cache invalidation and back-to-back publications, we've observed `cvmfs_talk reload sync` occasionally causing a client to revert to an earlier revision of a repo after fetching a stale copy of the manifest. 
It would probably be useful for the client to have a ratchet on the revision number to ensure that can never happen. 
This might be incompatible with rolling back a transaction, so perhaps as a flag to reload?

**Comment by HereThereBeDragons** [comment]
Should be fixed with #3156

**Comment by HereThereBeDragons** [comment]
closing, please reopen if it is not resolved
