### ISSUE TITLE
cvmfs_config fuser runs too long on host with afs

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3090]
On a system in Wisconsin that uses AFS, the `lsof` command run by `cvmfs_config fuser` takes forever to run and strace showed it doing lots of things under `/afs`.   We found that adding the `-e /afs` option made the lsof instead complete in 30 seconds, on a system that had 159 users.  The option fails with an error if `/afs` is not mounted, so first check to see if it is there before adding the option.

**Comment by DrDaveD** [comment]
The problem exists on all cvmfs-server versions that include the `cvmfs_config fuser` command, including version 2.10.0.

**Comment by jblomer** [comment]
@DrDaveD Is #3131 looking good to you?

**Comment by DrDaveD** [comment]
@cvuosalo Can you please test #3131 on your afs system?  You can easily hack it into a script.
