### ISSUE TITLE
v2.10 gateway compatibility issue: "json: cannot unmarshal number into Go struct field .tag_channel of type string" invalid request body

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/cvmfs#3097]
Hello,

We found that when a publisher node was upgraded to 2.10, while the stratum 0 (gateway) remained v2.9, we started getting this error when publishing:
```
Using auto tag 'generic-2022-11-09T18:28:26Z'
Processing changes...
Waiting for upload of files before committing...
Committing file catalogs...
Wait for all uploads to finish
Exporting repository manifest
Killed
Synchronization failed

Executed Command:
cvmfs_swissknife sync -u /cvmfs/soft.computecanada.ca -s /var/spool/cvmfs/soft.computecanada.ca/scratch/current -c /var/spool/cvmfs/soft.computecanada.ca/rdonly -t /var/spool/cvmfs/soft.computecanada.ca/tmp -b 03a3e2d152af1a5058a59bcf7907bbb271384762-shake128 -r gw,/srv/cvmfs/soft.computecanada.ca/data/txn,http://cvmfs-s0-soft.computecanada.ca:4929/api/v1 -w http://cvmfs-s0-soft.computecanada.ca:8000/cvmfs/soft.computecanada.ca -o /var/spool/cvmfs/soft.computecanada.ca/tmp/manifest -e shake128 -Z default -C /etc/cvmfs/repositories.d/soft.computecanada.ca/trusted_certs -N soft.computecanada.ca -K /etc/cvmfs/keys/soft.computecanada.ca.pub -L -D generic-2022-11-09T18:28:26Z -H /etc/cvmfs/keys/soft.computecanada.ca.gw -P /var/spool/cvmfs/soft.computecanada.ca/session_token -f overlayfs -p -l 4194304 -a 8388608 -h 16777216 -i
```

and on the stratum 0:
```
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832743]: CVMFS receiver started
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832743]: PayloadProcessor - lease_path: soft.computecanada.ca/, header digest: faec992cfd2f5cbbffb659519643b14eb1fc1d08, header size: 124
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"actions","req_id":"cb3cae57-c5ee-4a1b-b6a6-a086de2cb7f9","req_dt":143.549542,"action":"submit_payload","outcome":"success","action_dt":143.36482,"message":"action complete"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"http","req_id":"cb3cae57-c5ee-4a1b-b6a6-a086de2cb7f9","req_dt":143.580239,"message":"request_processed"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832743]: CVMFS receiver finished
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"http","req_id":"80cae2bd-0432-41c0-868c-b1100cd44cc0","req_dt":0.007132,"method":"POST","url":"/api/v1/payloads","t0":"2022-11-09T10:29:31-08:00","message":"request received"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832750]: CVMFS receiver started
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832750]: PayloadProcessor - lease_path: soft.computecanada.ca/, header digest: 84279c91b8b9e29fe07fc664ca5276c0ab480b25, header size: 79
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"actions","req_id":"80cae2bd-0432-41c0-868c-b1100cd44cc0","req_dt":119.390277,"action":"submit_payload","outcome":"success","action_dt":118.478115,"message":"action complete"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"http","req_id":"80cae2bd-0432-41c0-868c-b1100cd44cc0","req_dt":119.417477,"message":"request_processed"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_receiver[832750]: CVMFS receiver finished
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"info","component":"http","req_id":"4adc80a2-7b11-428a-9a31-aca322cd569f","req_dt":0.003674,"method":"POST","url":"/api/v1/leases/ZFWZVENLLLXE5FTY66J76AFK642BLMSU4JNSRRSCVHHLZ5GRQPMQ====","t0":"2022-11-09T10:29:31-08:00","message":"request received"}
Nov 09 10:29:31 cvmfs-s0-soft.computecanada.ca cvmfs_gateway[527314]: {"level":"error","component":"http","req_id":"4adc80a2-7b11-428a-9a31-aca322cd569f","req_dt":0.128469,"error":"json: cannot unmarshal number into Go struct field .tag_channel of type string","message":"invalid request body"}
```

The error went away when the publisher was downgraded back to 2.9.
Is it advisable/required/documented that the gateway and stratum 0 need to be the same version?

Thanks.

**Comment by mboisson** [comment]
Or that the stratum0 must be upgraded before the gateway is

**Comment by jblomer** [comment]
Thanks for the report!  I will clarify this in the release notes.

We overlooked this case when we removed support for "channels" in the manifest.

**Comment by mboisson** [comment]
> For gateway deployments, the gateway needs to be updated before or in lockstep with the publishers. Due to a ([backwards compatibility bug](https://github.com/cvmfs/cvmfs/issues/3097)) in the 2.10 gateway, remote publishers with a version <2.10 unfortunately cannot publish to a 2.10 gateway.


I don't think that describes this issue. 

Do you mean that the *stratum0* must be upgraded before the *gateway*/*publisher* ? 

And that 2.10 gateways can not publish to `<2.10` stratum0 ?

In our case, it is the gateway/publisher which was auto-updated before the stratum0 was updated, and that is what caused the issue

**Comment by mboisson** [comment]
I think the note should be reworded as: 

> For gateway deployments, the stratum 0 needs to be updated before or in lockstep with the publishers. Due to a (https://github.com/cvmfs/cvmfs/issues/3097) in the 2.10 gateway, publishers with a version 2.10 unfortunately cannot publish to a <2.10 stratum 0.

**Comment by rptaylor** [comment]
Jakob's terminology is correct; the gateway and stratum 0 could in principle be different but for our purposes they are interchangeable, so I just say stratum 0 out of habit.

On the other hand Maxime is correct that in our situation, it was a 2.10 publisher that had an error with a 2.9 gateway.

So if it is true that "remote publishers with a version <2.10 unfortunately cannot publish to a 2.10 gateway", combined with what we observed: a 2.10 publisher cannot publish to a 2.9 gateway, it means the gateway and publisher versions must match exactly.
Edit: okay I see that is what the updated release note says.

In practice that would mean we will have to update our dev and prod gateways at the same time, not allowing for a testing period on dev first. Hopefully that will be fine for this case, and presumably backwards compatibility will (at least usually) be possible going forwards.

**Comment by jblomer** [comment]
I can confirm, the goal is certainly to allow different versions of publisher and gateway to work together. This got unfortunately mixed up with this release.

**Comment by rptaylor** [comment]
Is this considered a documentation bug (in which case it could be closed) or should we expect a patch for it?

**Comment by jblomer** [comment]
Thanks for the reminder.  I'll close it as documentation bug.  Please feel free to reopen if needed.

**Comment by rptaylor** [comment]
In the other direction, it seems like a 2.9 publisher with a 2.10 gateway works.
