### ISSUE TITLE
let smalloc ride out temporary oom conditions

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3105]
smalloc() aborts if an allocation fails. If a client is experiencing a temporary OOM condition this can blow up a mount. It might be preferable to have smalloc() do back-off and retry for a bit before giving up.

**Comment by jblomer** [comment]
That's an interesting idea!  Did you already try it out?

**Comment by HereThereBeDragons** [comment]
PR for example: https://github.com/cvmfs/cvmfs/pull/3244
