### ISSUE TITLE
Cmake error Extracting libressl-3.5.3.tar.gz

### ISSUE THREAD

**Issue by computezrmle** [cvmfs/cvmfs#3109]
After a major system upgrade to the recent Tumbleweed version I had to recompile the CVMFS client.
Source:
https://github.com/cvmfs/cvmfs/archive/refs/heads/cvmfs-2.10.zip

`cmake ../` fails with the following error message:
```
--> Extracting libressl-3.5.3.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
CMake Error at CMakeLists.txt:208 (message):
  bootstrapping failed
```

The file libressl-3.5.3.tar.gz is included twice in the downloaded zip:
```
-rwxrwxrwx 1  28  9. Nov 07:39 ./externals/libcrypto/libressl-3.5.3.tar.gz
-rw-r--r-- 1  3,9M  9. Nov 07:39 ./externals/ssl/libressl-3.5.3.tar.gz
```

Repairing the link or replacing the file in ./externals/libcrypto with the file in /externals/ssl solves the cmake issue.

**Comment by jblomer** [comment]
Thanks for the report!  Please note that the zip file on github is automatically generated but it is _not_ our source distribution.  You can get a working source tarball from https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.10.0/source.tar.gz

**Comment by computezrmle** [comment]
@jblomer 
I confirm this issue can be solved using the tarball you mentioned.
