### ISSUE TITLE
Cmake error Patching leveldb

### ISSUE THREAD

**Issue by computezrmle** [cvmfs/cvmfs#3110]
After a major system upgrade to the recent Tumbleweed version I had to recompile the CVMFS client.
Source:
https://github.com/cvmfs/cvmfs/archive/refs/heads/cvmfs-2.10.zip

`cmake ../` fails with the following error message:
```
--> Patching leveldb
patching file build_detect_platform
patching file build_detect_platform
Hunk 1 FAILED 185/185.
     fi
 
     # Test whether tcmalloc is available
-    $CXX $CXXFLAGS -x c++ - -o $CXXOUTPUT -ltcmalloc 2>/dev/null  <<EOF
-      int main() {}
-EOF
-    if [ "$?" = 0 ]; then
-        PLATFORM_LIBS="$PLATFORM_LIBS -ltcmalloc"
-    fi
+#    $CXX $CXXFLAGS -x c++ - -o $CXXOUTPUT -ltcmalloc 2>/dev/null  <<EOF
+#      int main() {}
+#EOF
+#    if [ "$?" = 0 ]; then
+#        PLATFORM_LIBS="$PLATFORM_LIBS -ltcmalloc"
+#    fi
 
     rm -f $CXXOUTPUT 2>/dev/null
 fi
CMake Error at CMakeLists.txt:208 (message):
  bootstrapping failed
```

  
To solve this issue I had to disable leveldb in the cmake configuration.

**Comment by jblomer** [comment]
This may be solved by using the source tarball linked in #3109

**Comment by computezrmle** [comment]
@jblomer 
The same build error happens with the tarball from cern.ch.

**Comment by jblomer** [comment]
Hm, what version of `patch` is running on that system?

Can you check manually:

- in the cvmfs sources, under externals/leveldb extract the leveldb-1.18 tarball
- cd into leveldb-1.18
- Try to run `patch -p0 < ../src/dont_search_snappy.patch`

**Comment by computezrmle** [comment]
> Hm, what version of patch is running on that system?

Thanks.
This hint leads to a working solution.


On Tumbleweed `patch` from BusyBox is installed instead of `patch` from GNU:
`BusyBox v1.35.0 () multi-call binary.`

The build process tries to apply 2 patches to leveldb:
`patch -p0 < ../src/dont_search_snappy.patch`
`patch -p0 < ../src/dont_search_tcmalloc.patch`

With BusyBox the order matters.
While the 1st patch succeeds, the 2nd patch fails (tested reversing the order).

After replacing `BusyBox patch` with `GNU patch 2.7.6` from the TW repo both patches can be applied and order doesn't matter any more.
The build process then completes without any further issues.
