### ISSUE TITLE
Can't evict chunks from cache

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3122]
Context: We have a process that runs on each CVMFS client that reads a database file that is changed on every repo update. When the client has been idle for some time, and repo updates have been frequent, the useful cache contents get pushed out by accumulated   database chunks. We'd like to explicitly evict these as soon as the processing is complete to prevent cache poisoning.
It appears that its is not possible to explicitly evict a chunked file via the cvmfs_talk socket interface.

```
# cvmfs_talk -i REPO cache list  | grep '/.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite'
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite
Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite

# cvmfs_talk -i REPO  evict '/.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite'
No such regular file

# cvmfs_talk -i REPO  evict 'Part of /.cvmfs/snapshots/generic-2022-11-30T19:57:13Z/metadata.sqlite'
No such regular file
```

Desired behaviour: 

```
cvmfs_talk -i REPO  evict '/file'
```
evicts all `Part of /file` chunks from cache

**Comment by jblomer** [comment]
Indeed, that was never implemented.  Should be easy to add.  The manual eviction is hardly ever used, I think.  Is it part of your regular workflow?  If so, we may rather want to tune the automatic cache eviction.

**Comment by mharvey-jt** [comment]
See PR #3129
