### ISSUE TITLE
Multiple cvmfs_server check -a processes running

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3136]
On an out of service but full size stratum 1 I have this cron entry
```
8 0 * * 0-6 root cvmfs_server check -a
```
so that once a day it tries to start a `cvmfs_server check -a` series.  The machine has been up for 8 months, and I just noticed today that there are 3 checks running.  The code does an `acquire_lock` so it's not supposed to run more than one.  I did a ps on each of the parent shells and found that they did indeed all have file descriptor 9 open on `/var/spool/cvmfs/is_checking_all.lock`, but 2 of the 3 were marked with `(deleted)`.  I don't understand how that can happen.  The corresponding `release_lock` is only called if the `acquire_lock` succeeds.

This is running cvmfs-server-2.10.0-1.1.osg36.el7, although it's quite possible that it has been upgraded since the last boot.

**Comment by jblomer** [comment]
Is this something you can further investigate or do you want us to take a look?

**Comment by DrDaveD** [comment]
At this point I'm just considering this issue to be a placeholder, to see if it happens again.  I looked at the two machines where I have `cvmfs_server check -a` running, and at this point they still each have only one.

**Comment by DrDaveD** [comment]
I don't know, perhaps it happened because of an upgrade (or two).  The other machine is still using cvmfs-server-2.9.3.

**Comment by HereThereBeDragons** [comment]
closed for now. please reopen if issue occures again
