### ISSUE TITLE
cvmfs_server check can be extremely slow with many references to deduplicated files

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3138]
I have seen extremely long cvmfs_server check times, on the order of months, especially in repositories that have many references to deduplicated files, such as unpacked.cern.ch and singularity.opensciencegrid.org.  It would be good if they only got checked once, because otherwise each check turns into an http request.

**Comment by jblomer** [comment]
We still need to discuss who is going to work on this.

**Comment by HereThereBeDragons** [comment]
Duplication of issue #3000. I will close the other because this has one here more interaction

**Comment by DrDaveD** [comment]
Good news: the check of unpacked.cern.ch on the Nebraska backup stratum 1 took only 2-1/2 days, a huge improvement over the  greater than 3 months I saw before.

**Comment by jblomer** [comment]
That's great! Many thanks for the feedback.  Do you by chance have a record of the peak memory usage?

**Comment by DrDaveD** [comment]
I don't, but I can say that cms.cern.ch has been running since late Saturday (3-1/2 days so far) and it currently has a resident memory size of 1.2g and virtual memory size of 1.4g.

**Comment by jblomer** [comment]
Great!  That looks still manageable.
