### ISSUE TITLE
create cvmfs stratum 0 with s3 backend fail.

### ISSUE THREAD

**Issue by traldi** [cvmfs/cvmfs#3140]
Hi,
I'm following this documentation : 
https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#s3-compatible-storage-systems

To create a repository for a cvmfs stratum 0 repo using s3 with an Openstack Swift exposing the S3 interface.

I do:
s3cmd --configure
export AWS_ACCESS_KEY_ID=XXX
export AWS_SECRET_ACCESS_KEY=XXX
s3cmd mb s3://cvmfs
s3cmd --acl-public setacl s3://cvmfs

And everythings work fine.

When I try to create the repo I have this error:
root@cvmfs-s0-datacloud:~# cvmfs_server mkfs -s cvmfs_s3.cfg -w https://s3.cloud.infn.it/cvmfs datacloud.infn.it
Owner of datacloud.infn.it [root]:
Creating Configuration Files... done
Creating CernVM-FS Master Key and Self-Signed Certificate... done
Creating CernVM-FS Server Infrastructure... done
Signing 30 day whitelist with master key... done
Creating Initial Repository... HTTP protocol error 400: https://s3.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfsreflog (9)
failed loading reflog (3 - network failure)
reflog missing
fail! (cannot sign repo)

The file cvmfs_s3.cfg is:
cat cvmfs_s3.cfg
CVMFS_S3_ACCESS_KEY=XXXXXXXXX9a7e1ad981XXXXXXXX
CVMFS_S3_SECRET_KEY=XXXXXXXXXXXXXbc993085XXXXXX
CVMFS_S3_HOST=s3.cloud.infn.it
CVMFS_S3_BUCKET=cvmfs
CVMFS_S3_PORT=443
CVMFS_S3_DNS_BUCKETS=false
CVMFS_S3_USE_HTTPS=true

Someone can help me to understand what's goes wrong

**Comment by HereThereBeDragons** [comment]
Hi,
The only thing that seems a bit off to me is the URL in the `-w` argument. It should be of format `https://<bucketname>.<host>`

So I guess for you it should be `https://cvmfs.s3.cloud.infn.it`

Could you please try this?

Edit: You might also need to add the port.. not sure

**Comment by traldi** [comment]
Hi,
thanks for the answer, ... yes I tried also with tahd syntax:

cvmfs_server mkfs -s /root/cvmfs_s3.cfg -w https://cvmfs.s3.cloud.infn.it datacloud.infn.it
Owner of datacloud.infn.it [root]:
Creating Configuration Files... done
Creating CernVM-FS Master Key and Self-Signed Certificate... done
Creating CernVM-FS Server Infrastructure... done
Signing 30 day whitelist with master key... done
Creating Initial Repository... HTTP connection error 4: https://cvmfs.s3.cloud.infn.it/datacloud.infn.it/.cvmfsreflog
failed loading reflog (3 - network failure)
reflog missing
fail! (cannot sign repo)

**Comment by traldi** [comment]
Also with the prot I tried:
cvmfs_server mkfs -s /root/cvmfs_s3.cfg -w https://cvmfs.s3.cloud.infn.it:443 datacloud.infn.it
Owner of datacloud.infn.it [root]:
Creating Configuration Files... done
Creating CernVM-FS Master Key and Self-Signed Certificate... done
Creating CernVM-FS Server Infrastructure... done
Signing 30 day whitelist with master key... done
Creating Initial Repository... HTTP connection error 4: https://cvmfs.s3.cloud.infn.it:443/datacloud.infn.it/.cvmfsreflog
failed loading reflog (3 - network failure)
reflog missing
fail! (cannot sign repo)

There is a way to dectript .cvmfsredlog file I obtain it using s3 command, but it is a crypted file.

I try to download the file:
s3cmd -c s3.cfg get s3://cvmfs/datacloud.infn.it/.cvmfsreflog cvmfsreflog

And I try to open the file using:
 cvmfs_swissknife hash -a shake128 <  cvmfsreflog
or
 cvmfs_swissknife hash -a sha1 <  cvmfsreflog

But cvmfs_swissknife has not hast command

Cheers
Sergio

**Comment by HereThereBeDragons** [comment]
.cvmfsreflog is a sqlite file. so its not encrypted. You should see something like
`Wtablerefsrefs^DCREATE TABLE refs (hash TEXT, type INTEGER, timestamp INTEGER, CONSTRAINT pk_refs PRIMARY KEY (hash))`

But ok, the file is create on the bucket, but it cannot be read.
Can you check if you can pull it with wget for https?
Something like `wget https://cvmfs.s3.cloud.infn.it/datacloud.infn.it/.cvmfsreflog`

**Comment by traldi** [comment]
Hi I try these commands:

wget https://cvmfs.s3.cloud.infn.it/datacloud.infn.it/.cvmfsreflog
--2022-12-14 09:26:53--  https://cvmfs.s3.cloud.infn.it/datacloud.infn.it/.cvmfsreflog
Resolving cvmfs.s3.cloud.infn.it... failed: Name or service not known.
wget: unable to resolve host address “cvmfs.s3.cloud.infn.it”

wget https://s3.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfsreflog
--2022-12-14 09:27:19--  https://s3.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfsreflog
Resolving s3.cloud.infn.it... 90.147.176.141, 90.147.176.8
Connecting to s3.cloud.infn.it|90.147.176.141|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-12-14 09:27:19 ERROR 400: Bad Request.

wget --no-check-certificate https://s3.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfsreflog
--2022-12-14 09:27:34--  https://s3.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfsreflog
Resolving s3.cloud.infn.it... 90.147.176.141, 90.147.176.8
Connecting to s3.cloud.infn.it|90.147.176.141|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-12-14 09:27:34 ERROR 400: Bad Request.

Seems the bucket is not public. Some colleauges of mine are working to do the bucket public.

I set it using:
s3cmd -c s3.cfg --acl-public setacl s3://cvmfs
s3://cvmfs/: ACL set to Public

But may be ot is not enought.

**Comment by traldi** [comment]
We foud the problem in -w we have to put the V1 version and a different url:
cvmfs_server mkfs -s /root/cvmfs_s3.cfg -w https://stor.cloud.infn.it/v1/AUTH_79322ee743c74382ad9de8b1d895616a/cvmfs datacloud.infn.it

May be with -w option the api are not equal to V1 or V2 or the endpoint was not well published using the name server

**Comment by HereThereBeDragons** [comment]
Great to hear you found a solution!
I will close this now but feel free to open it up if there are more issues
