### ISSUE TITLE
Error when creating sqlite-backed NFS maps

### ISSUE THREAD

**Issue by lflis** [cvmfs/cvmfs#3150]
Dear CVMFS Team,

It seems new cvmfs build for Centos 7 has some issues with creating sqlite based nfsmaps:

```text
mount /cvmfs/cms.cern.ch
CernVM-FS: running with credentials 993:991
CernVM-FS: loading Fuse module... cvmfs2: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc7/build/BUILD/cvmfs-2.10.0/cvmfs/nfs_maps_sqlite.cc:154: static NfsMapsSqlite* NfsMapsSqlite::Create(const string&, uint64_t, bool, perf::Statistics*): Assertion `retval == 0' failed.

[root@cvmfs02 ~]# rpm -qa | egrep 'cvmfs|sqlite'
cvmfs-release-2-6.noarch
cvmfs-config-kek-1.0-6.noarch
sqlite-3.7.17-8.el7_7.1.x86_64
cvmfs-virgo.ego-gw.it-pub-key-1-1.x86_64
cvmfs-config-default-2.0-1.noarch
cvmfs-2.10.0-1.el7.x86_64
```

**Comment by vvolkl** [comment]
Hi @lflis, could you paste the full output and the command you are running to get the error? Thanks!

**Comment by lflis** [comment]
Hi
Output in the initial post is all we do:

Command:
 mount /cvmfs/cms.cern.ch

Stdout+stderr
CernVM-FS: running with credentials 993:991
CernVM-FS: loading Fuse module... cvmfs2: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/cc7/build/BUILD/cvmfs-2.10.0/cvmfs/nfs_maps_sqlite.cc:154: static NfsMapsSqlite* NfsMapsSqlite::Create(const string&, uint64_t, bool, perf::Statistics*): Assertion `retval == 0' failed.

And command fails. FS is not mounted. 
Filesystems that were created prior upgrading work fine (they have nfsmaps created by older version) . CMS filesystem is a new fs we try to mount for the first time

Hope that helps

**Comment by vvolkl** [comment]
Thanks for the clarification! Unfortunately I still cannot reproduce the issue. As I understand it you ran the setup with an older version of the client, then upgraded and ran the mount command? Which version are you upgrading from, 2.9? What is your confguration (`cvmfs_config showconfig cms.cern.ch`)? 

I've tried installing cvmfs-2.8.2 on a centos7 machine, disabling autofs, upgrading cvmfs and mounting cms.cern.ch and did not see an error. Any additional information to reproduce the error would be very helpful.

**Comment by DrDaveD** [comment]
I'm guessing that the most significant config parameter is CVMFS_NFS_SHARED.

**Comment by DrDaveD** [comment]
According to https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#shared-nfs-maps-ha-nfs the /etc/exports and /etc/fstab entries may also be relevant.

**Comment by lflis** [comment]
Hi. I confirm what @DrDaveD said. CVMFS_NFS_SHARED option is a key here as it turns on nfs maps and sqlite codepath

fstab:
cms.cern.ch           /cvmfs/cms.cern.ch    cvmfs  defaults,noauto        0 0

default.local
CVMFS_CACHE_BASE=/cvmfs-data/cache/
CVMFS_QUOTA_LIMIT=190000
CVMFS_HTTP_PROXY="http://149.156.z.xyz:3128"
CVMFS_MEMCACHE_SIZE=768
CVMFS_NFS_SOURCE=yes
CVMFS_NFS_SHARED=nfs_shared_data
CVMFS_MAX_RETRIES=3
CVMFS_SHARED_CACHE=no

**Comment by jblomer** [comment]
Let's try mounting in debug mode.  Please set `CVMFS_DEBUGLOG=/tmp/cvmfs.log` in your /etc/cvmfs/default.local file. The debug log file should tell us more about the cause of the error.

**Comment by lflis** [comment]
```
(cvmfs) looks like cvmfs has been crashed previously    [01-13-2023 16:38:19 CET]
(cvmfs) setting up cache manager instance default    [01-13-2023 16:38:19 CET]
(quota) rebuild database, unlinking existing (./cachedb)    [01-13-2023 16:38:19 CET]
(cvmfs) SQlite3: duplicate column name: type in "ALTER TABLE cache_catalog ADD type INTEGER; ALTER TABLE cache_catalog ADD pinned INTEGER" (1)    [01-13-2023 16:38:19 CET]
(cvmfs) CernVM-FS: building lru cache database...    [01-13-2023 16:38:19 CET]
(quota) re-building cache database    [01-13-2023 16:38:19 CET]
(quota) rebuilding finished, seqence 0, gauge 0    [01-13-2023 16:38:19 CET]
(quota) free space: 260065 MB    [01-13-2023 16:38:19 CET]
(cvmfs) CernVM-FS: quota initialized, current size 0MB    [01-13-2023 16:38:19 CET]
(nfs maps) Ignoring rebuild flag as this may crash other cluster nodes.    [01-13-2023 16:38:19 CET]
(cvmfs) SQlite3: no such column:  in "INSERT INTO inodes (rowid, path) VALUES (?, "");" (1)    [01-13-2023 16:38:19 CET]
```

**Comment by jblomer** [comment]
Hm, the SQlite NFS maps file may be broken. Try removing `nfs_map_.*` from the cache directory and remount.

**Comment by lflis** [comment]
```
(cvmfs) setting up cache manager instance default    [01-13-2023 16:53:04 CET]
(cvmfs) SQlite3: duplicate column name: type in "ALTER TABLE cache_catalog ADD type INTEGER; ALTER TABLE cache_catalog ADD pinned INTEGER" (1)    [01-13-2023 16:53:04 CET]
(cvmfs) CernVM-FS: building lru cache database...    [01-13-2023 16:53:04 CET]
(quota) re-building cache database    [01-13-2023 16:53:04 CET]
(quota) rebuilding finished, seqence 0, gauge 0    [01-13-2023 16:53:04 CET]
(quota) free space: 260059 MB    [01-13-2023 16:53:04 CET]
(cvmfs) CernVM-FS: quota initialized, current size 0MB    [01-13-2023 16:53:04 CET]
(cvmfs) SQlite3: no such column:  in "INSERT INTO inodes (rowid, path) VALUES (?, "");" (1)    [01-13-2023 16:53:04 CET]
```

```
[root@cvmfs02 nfs_maps.cms.cern.ch]# sqlite3 inode_maps.db 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .dump
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE inodes (path TEXT PRIMARY KEY);
COMMIT;
```

**Comment by jblomer** [comment]
Is this from the original database or the recreated one after it was deleted?

Update: I think I can reproduce the issue, looking further.

**Comment by jblomer** [comment]
Still puzzled why the table initialization fails.  As a workaround, you can insert the root entry yourself with `sqlite3`:
```
insert into inodes (rowid, path) values (256, "");
```
Afterwards, it should mount.

(NB: the sqlite backed NFS maps is a very rare configuration and likely to be deprecated in the future. Any chance you can switch to the regular leveldb nfs maps? If possible, it would be even better to use the regular cvmfs clients on the nodes as it is not affected by some known bugs inherent to NFS export.)

**Comment by lflis** [comment]
Thank you for the workaround and suggestions. 
We prefer to use NFS export as we have mostly diskless nodes and shared and non-local cache is something that simpifies the setup a lot

I tried to use the following workaround earlied (as code is trying to do) but it didn't help. Changing 1 to 256 fixed the problem
```
INSERT INTO inodes (rowid, path) VALUES (1, "");
```
