### ISSUE TITLE
High limit of open file descriptors slows down `exec` wrapper

### ISSUE THREAD

**Issue by jblomer** [cvmfs/cvmfs#3158]
The cvmfs utility code that wraps `exec` closes all possible open file descriptors (with some exceptions) before starting the new process.  That becomes an issue as the limit on open file descriptors gets very high, as found in [this post](https://cernvm-forum.cern.ch/t/cvmfs-config-setup-hangs/275)

**Comment by gman0** [comment]
Thanks.
