### ISSUE TITLE
ENOSPC preferable to EIO when cache is out of space

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3191]
If the cache storage is full,  fuse operations return EIO. It would be preferabgle if this could be ENOSPC - it would be less confusing for users, and give them a hint at what the problem might be (and so hopefully result in fewer support tickets)

**Comment by HereThereBeDragons** [comment]
Closing as not of intereste anymore. They now make sure that the cache partition never fills up
