### ISSUE TITLE
sqlite readahead optimisation 1/2

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3192]
1) The cache readahead does so in 4kiB blocks  - this should be coalesced into a single large read
2) The readahead should be omitted altogether when the cache is on a tmpfs, as it's already in the page cache (see https://stackoverflow.com/questions/26635846/how-to-tell-if-a-file-is-on-tmpfs-given-its-path-on-linux for how to determine)

**Comment by mharvey-jt** [comment]
https://github.com/cvmfs/cvmfs/pull/3250 addresses point 2

**Comment by jblomer** [comment]
@HereThereBeDragons Is the first point also addressed?

**Comment by HereThereBeDragons** [comment]
nope not yet. reopen

**Comment by HereThereBeDragons** [comment]
Related #3315 and #3316

**Comment by HereThereBeDragons** [comment]
closing this part as the missing improvement (point 1 .. the 4kiB reads) are tracked in issue #3335
