### ISSUE TITLE
HTTPS connections always trigger authz helper

### ISSUE THREAD

**Issue by jblomer** [cvmfs/cvmfs#3213]
The authz client authentication should _only_ be used if `CVMFS_AUTHZ_HELPER` is set. Currently, there is an unconditional (failed) attempt to use the authz helper when the client connects through HTTPS.

**Comment by HereThereBeDragons** [comment]
Should be part of download manager refactor #3095

**Comment by HereThereBeDragons** [comment]
#3333 will most likely superseed #3307

**Comment by HereThereBeDragons** [comment]
#3333 is the merged PR
