### ISSUE TITLE
`cvmfs2` at 100% CPU

### ISSUE THREAD

**Issue by rklasen** [cvmfs/cvmfs#3222]
Hi,

since a week or so I'm having trouble mounting cmvfs shares. I have to apologize in advance because I don't think it's a bug in cvmfs but rather in how I use it. Since I don't know where to start I could use some help in debugging. 

Background: I'm using the cvmfs docker image to mount the FairRoot binaries from GSI. I prepared a dockerfile that inherits from the official image and only added our host keys and the repo config. This is what the dockerfile looks like:

```
FROM cvmfs/service

ENV CVMFS_CLIENT_PROFILE=single
ENV CVMFS_HTTP_PROXY=DIRECT
ENV CVMFS_REPOSITORIES=fairsoft.gsi.de

COPY fairsoft.gsi.de.conf /etc/cvmfs/config.d/fairsoft.gsi.de.conf
COPY masterkey.gsi.de.pub /etc/cvmfs/keys/masterkey.gsi.de.pub
```

The puclic key is probably obvoius and the config is:

```
CVMFS_SERVER_URL="http://cvmfs-s1.gsi.de/cvmfs/fairsoft.gsi.de"
CVMFS_HTTP_PROXY="DIRECT"
CVMFS_PUBLIC_KEY="/etc/cvmfs/keys/masterkey.gsi.de.pub"
```

---

I've been using this setup without issue for about a year now, I simply start my docker container and have instant access to the mounts. I've uploaded my docker image to the docker hub, so if you want to test it, you can with:

```
sudo docker run --rm --privileged --cap-add SYS_ADMIN --device /dev/fuse --volume /cvmfs:/cvmfs:shared --name cvmfs rklasen/cvmfs
```

Now, on my machine, this startup freezes at the line

```
[INF] mounting cvmfs-config.cern.ch fairsoft.gsi.de
```

for about five minutes and consumes an entire thread:

![image](https://user-images.githubusercontent.com/13201731/221843533-5bd2a46d-6e02-47d1-bc26-37a511d4379e.png)

After that, the script goes in the service life cycle and I can access the mounts:

```
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/cvmfs-config.cern.ch
CernVM-FS: loading Fuse module... done
CernVM-FS: mounted cvmfs on /cvmfs/fairsoft.gsi.de
[INF] done mounting, entering service life cycle
```

But the CPU usage remains at 100%. What's weird is that it works fine in a fresh Ubuntu virtual machine on that same host, so it can't be network related. In the VM, the time from start to service cycle is a couple of seconds, not minutes.

Can anyone help me debug this?

**Comment by jblomer** [comment]
This may be related to a high limit of open file descriptors: #3158 #3199

You can try starting the docker container with `docker run --ulimit nofile=10000:10000` for a more reasonable limit.

**Comment by rklasen** [comment]
Thanks for the quick reply, that indeed fixes the issue!
