### ISSUE TITLE
Reduce lock scope/duration for catalog load

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3236]
Only take write lock when attaching a catalog.
Do not take a lock for the time during which the catalog is being downloaded

**Comment by HereThereBeDragons** [comment]
Should be part of refactor load catalog #3031

**Comment by mharvey-jt** [comment]
@jblomer could this be a 2.11 milestone?

**Comment by HereThereBeDragons** [comment]
Should have been addressed by #3476
( a bit different solution where opportunistically catalogs are downloaded before they are actually handled)
