### ISSUE TITLE
Problem with Publisher - cannot load whitelist

### ISSUE THREAD

**Issue by traldi** [cvmfs/cvmfs#3243]
I istalled a Stratum 0 cvmfs working with S3 as backend.
I install the gateway in the host and it seems work fine:

From remote host (host1):
[ubuntu@host1 ~]$ curl http://cvmfs.wp6.cloud.infn.it:4929/api/v1/repos | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    82  100    82    0     0   3904      0 --:--:-- --:--:-- --:--:--  3904
{
  "data": {
    "datacloud.infn.it": {
      "keys": {
        "keygw": "/"
      },
      "enabled": true
    }
  },
  "status": "ok"
}

[ubuntu@host1 ~]$ curl http://cvmfs.wp6.cloud.infn.it:4929/api/v1/repos/datacloud.infn.it | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    60  100    60    0     0   2727      0 --:--:-- --:--:-- --:--:--  2727
{
  "data": {
    "keys": {
      "keygw": "/"
    },
    "enabled": true
  },
  "status": "ok"
}

I tried from host1 to set up a publisher and I copy the relative key in /tmp/datacloud.infn.it_keys directory and I use this command:

[ubuntu@host1 ~]$ sudo cvmfs_server mkfs -w http://cvmfs.wp6.cloud.infn.it/cvmfs/datacloud.infn.it \
                                                                         -u gw,/srv/cvmfs/datacloud.infn.it/data/txn,http://cvmfs.wp6.cloud.infn.it:4929/api/v1 \
                                                                         -k /tmp/datacloud.infn.it_keys -o  `whoami`  datacloud.infn.it

But I have a failure:
Creating Configuration Files... done
Importing CernVM-FS Master Key and Certificate from '/tmp/datacloud.infn.it_keys'... done
Creating CernVM-FS Server Infrastructure... done
Creating Initial Repository... done
Mounting CernVM-FS Storage... (overlayfs) waiting for apache... fail

In the CVMFS stratum0 logs I do not found any erros or warnings.

In the host1 ( publisher) I foud:
cvmfs publisher cannot load whitelist [failed to download whitelist]

Any hints?

**Comment by HereThereBeDragons** [comment]
Hi traldi
Could you please try out if you get a reply for this when running on your publisher? 
`curl http://cvmfs.wp6.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfspublished`

From the error message it seems like it's a problem that the curl cannot reach the endpoint. Are you sure that on your stratum 0 the appropriate ports are open? See in the developer doc https://github.com/cvmfs/cvmfs/blob/devel/doc/developer/41-setup-cvmfs-gateway.md or in readthedocs https://cvmfs.readthedocs.io/en/stable/cpt-repository-gateway.html

Also please note that these kind of support questions are better handled in the forum: https://cernvm-forum.cern.ch

**Comment by traldi** [comment]
Hi,
if I try to curl the .cvmfspublished I have:
[ubuntu@host1 ~]# curl http://cvmfs.wp6.cloud.infn.it/cvmfs/datacloud.infn.it/.cvmfspublished
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at cvmfs.wp6.cloud.infn.it Port 80</address>
</body></html>

But the port has been opened. I have (from remote host):

[ubuntu@host1 ~]#telnet cvmfs.wp6.cloud.infn.it 80
Trying 192.135.24.217...
Connected to cvmfs.wp6.cloud.infn.it.
Escape character is '^]'.
^]
telnet> quit
Connection closed.


[ubuntu@host1 ~]#telnet cvmfs.wp6.cloud.infn.it 4929
Trying 192.135.24.217...
Connected to cvmfs.wp6.cloud.infn.it.
Escape character is '^]'.
^]
telnet> quit
Connection closed.

Let me know if I have to post the problem in forum (https://cernvm-forum.cern.ch/)

Thanks

**Comment by HereThereBeDragons** [comment]
Hi,
We can continue here, just for next time it would be better in the forum

This is odd. Do you have created your repo on the stratum 0? (e.g. you can do `cvmfs_server transaction  datacloud.infn.it` on the gateway?)
If not , you need to create your repo on the stratum 0 first and then the publisher just links to it (both is using `cvmfs_server mkfs`)

**Comment by traldi** [comment]
Hi,
yes if I'm inside the stratum 0 host (where also the gateway are running):

ubuntu@cvmfs-s0-datacloud:~$ sudo cvmfs_server transaction datacloud.infn.it

ubuntu@cvmfs-s0-datacloud:~$ sudo cp test.txt /cvmfs/datacloud.infn.it/

ubuntu@cvmfs-s0-datacloud:~$ sudo cvmfs_server publish datacloud.infn.it
Using auto tag 'generic-2023-03-23T13:54:55Z'
Processing changes...
Waiting for upload of files before committing...
Committing file catalogs...
Wait for all uploads to finish
Exporting repository manifest
Statistics stored at: /var/spool/cvmfs/datacloud.infn.it/stats.db
Tagging datacloud.infn.it
Flushing file system buffers
Signing new manifest
Remounting newly created repository revision

The repo exist and the gateway are running:
ubuntu@cvmfs-s0-datacloud:~$ sudo systemctl status cvmfs-gateway
● cvmfs-gateway.service - CernVM-FS Repository Gateway
     Loaded: loaded (/lib/systemd/system/cvmfs-gateway.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-03-22 12:14:15 CET; 1 day 2h ago
   Main PID: 2096620 (cvmfs_gateway)
      Tasks: 8 (limit: 4677)
     Memory: 9.3M
     CGroup: /system.slice/cvmfs-gateway.service
             └─2096620 /usr/bin/cvmfs_gateway

Mar 22 14:16:18 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"http","req_id":"9f48feb4-d809-4563-918d-8f747eab40fd","req_dt":0.0>
Mar 22 14:16:23 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"http","req_id":"2ef0eb6d-6be7-4cd6-bc5e-e46ee63c856b","req_dt":0.0>
Mar 22 14:16:23 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"actions","req_id":"2ef0eb6d-6be7-4cd6-bc5e-e46ee63c856b","req_dt":>
Mar 22 14:16:23 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"http","req_id":"2ef0eb6d-6be7-4cd6-bc5e-e46ee63c856b","req_dt":2.6>
Mar 22 14:17:53 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"http","req_id":"0bee5653-14c8-47ad-a3cf-02631abac959","req_dt":0.0>
Mar 22 14:17:53 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"actions","req_id":"0bee5653-14c8-47ad-a3cf-02631abac959","req_dt":>
Mar 22 14:17:53 cvmfs-s0-datacloud cvmfs_gateway[2096620]: {"level":"info","component":"http","req_id":"0
....

We created the repo about one 20 days ago. Then I installed gateway on monday (this week).

**Comment by HereThereBeDragons** [comment]
i had another look at your `mkfs` command. for s3 it has to be different. especially parameter `-s` and `-w` as shown here: https://github.com/cvmfs/cvmfs/blob/devel/doc/developer/41-setup-cvmfs-gateway.md

also you should double check if `whoami` gives you the correct owner you want when used with sudo

```
  # for repo "s3.test.repo" with S3 storage backend
  # you need to change -w and add -s the s3 config from the gateway
  cvmfs_server mkfs \
      -s /etc/cvmfs/cvmfs_s3.cfg \ 
      -w http://<URL to S3 bucket> \
      -u gw,/srv/cvmfs/s3.test.repo/data/txn,http://<URL to gateway>:4929/api/v1 \
      -k /home/myuser/tmpKeys  \
      -o `whoami` \
      s3.test.repo
 ```

**Comment by traldi** [comment]
Hi,
thanks to the good hint.
It is not need use -s with the s3 credential but in -w option we have to put he https://<real S3 bucket url>/<repo name>

The `whoami` I had checked the result was fine.

With the real url s3 the problem is solved. (We had the same problem when we install the Stratum 0 but I think it was just for that case).
Thanks

**Comment by HereThereBeDragons** [comment]
great you could solve it. i close this now
