### ISSUE TITLE
geoAPI lookups fail if proxy is not a valid hostname

### ISSUE THREAD

**Issue by rptaylor** [cvmfs/cvmfs#3255]
cvmfs-server-2.10.1-1.el8.x86_64

According to [the docs](https://github.com/cvmfs/doc-cvmfs/blob/latest/cpt-configure.rst#ordering-of-servers-according-to-geographic-proximity)

> The proxy address can be replaced by a UUID if no proxies are used, and the CernVM-FS client does that if there are no regular proxies. 

However while investigating https://github.com/cvmfs-contrib/cvmfs-servermon/issues/43 (not sure if related) I noticed that the API lookup failed in every case where the proxy name is not a valid resolvable host name:

```
$  curl http://localhost/cvmfs/soft-dev.computecanada.ca/api/v1.0/geo/cvmfs-stratum-one.cern.ch/cvmfs-s1fnal.opensciencegrid.org,cvmfs-stratum-one.cern.ch,cvmfs-stratum-one.ihep.ac.cn
2,1,3


$  curl http://localhost/cvmfs/soft-dev.computecanada.ca/api/v1.0/geo/`uuidgen`/cvmfs-s1fnal.opensciencegrid.org,cvmfs-stratum-one.cern.ch,cvmfs-stratum-one.ihep.ac.cn
Bad Request: remote addr not found in database
```

If the documentation is correct and clients are using random UUIDs in some cases, they will not get geoapi results.

I know this is a change in behaviour because I used to test this with a proxy name like whatever.example.org and it always worked.

**Comment by rptaylor** [comment]
Assuming the change in behaviour is unexpected (maybe related to a maxmind DB update or something?) I infer that the GeoAPI only measures the distance with respect to the client when the provided proxy string is not a valid resolvable hostname, otherwise it actually measures the distance with respect to the specified proxy server?

**Comment by DrDaveD** [comment]
If the "proxy" in the lookup string is not a valid host name, it falls back to using the host name that apache says is on the other end of the socket.  Because you are using http://localhost, it cannot look up geo information for 127.0.0.1.  Try it using a full host name of your host instead of localhost.

**Comment by rptaylor** [comment]
Oh, very unexpected! Okay it works that way, thanks @DrDaveD
