### ISSUE TITLE
tty permissions in centos7:latest

### ISSUE THREAD

**Issue by traylenator** [cvmfs/cvmfs#3257]
Steps to reproduce

```
apptainer run /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/sft/docker/centos7:latest
apptainer> python3 -c "import pty; pty.fork()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/pty.py", line 96, in fork
    master_fd, slave_fd = openpty()
  File "/usr/lib64/python3.6/pty.py", line 29, in openpty
    master_fd, slave_name = _open_terminal()
  File "/usr/lib64/python3.6/pty.py", line 59, in _open_terminal
    raise OSError('out of pty devices')
OSError: out of pty devices
```

Expected should import okay.

Trying on a plain centos7 VM without singularity:

```
python3 -c "import pty; pty.fork()"
```
is good. 

The following were also good.

apptainer with centos8:latest or centos9:latest is also okay.

```
podman  run -it gitlab-registry.cern.ch/linuxsupport/cc7-base:latest /bin/bash
```

Could not manage to get apptainer --fakeroot to work against linuxsupport/cc7-base:latest to check if that worked.

**Comment by jblomer** [comment]
I do see different owners for /dev/* in apptainer centos:7 vs. apptainer centos:8. In 7, it is `65534 nfsnobody`, in 8 it is `nobody:nobody`.

**Comment by DrDaveD** [comment]
That's just a difference in the definition of the user assigned to id 65534 on the different hosts, not a real difference in owners.

I don't understand why this is reported as a cvmfs issue.  I get the same failure from other centos7-based containers when using apptainer (from sl7 or rocky8) without suid, for example /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest.  It is probably a problem in centos7 python3 or other libraries not being compatible with user namespaces.

Yes I can reproduce it on el7 with `unshare -U python3 -c "import pty; pty.fork()"`, where that works OK on rocky8.
