### ISSUE TITLE
Unable to recover from publish failures (again)

### ISSUE THREAD

**Issue by chrisburr** [cvmfs/cvmfs#3278]
Similar to https://github.com/cvmfs/cvmfs/issues/3088, publish failures still aren't recoverable by aborting if the FUSE mount state is broken:

```bash
$ ls /cvmfs/lhcbdev.cern.ch
ls: reading directory /cvmfs/lhcbdev.cern.ch: Transport endpoint is not connected

$ cvmfs_server abort lhcbdev.cern.ch
You are about to DISCARD ALL CHANGES OF THE CURRENT TRANSACTION for lhcbdev.cern.ch!  Are you sure (y/N)? y
HTTP Uploader - Could not open session token file.
HTTP Uploader - Could not open session token file.
cannot retrieve root hash from read-only mount point
```

It seems to happen about once a week.

I currently have two lhcbdev publishers in this state if you want investigate.

**Comment by jblomer** [comment]
I can reproduce the problem, looking into how to fix it.

**Comment by jblomer** [comment]
As a workaround, you should be able to run the `abort` command after calling `cvmfs_suid_helper rdonly_umount lhcbdev.cern.ch`.

**Comment by chrisburr** [comment]
Thanks for fixing it and providing a cleaner workaround 😄
