### ISSUE TITLE
Update pacparser to version 1.4.2

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3282]
There's a new [security release version 1.4.2](https://github.com/manugarg/pacparser/releases/tag/v1.4.2) for pacparser.

**Comment by vvolkl** [comment]
It was previously noted (https://github.com/cvmfs/cvmfs/issues/2872#issuecomment-1123282535) that updating pacparser could add new python requirements that could be an issue for some currently supported platforms. I'll try this out and see which platforms are affected.
