### ISSUE TITLE
CVMFS and fuse-overlayfs  

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3286]
Hi,

Got a weird issue with CVMFS in conjunction with fuse-overlayfs as an unprivileged user.  Here's the situation:

A world-writable directory on CVMFS:
```
ls -l /cvmfs/repo/entrypoint
drwxrwxrwx 2 root root   35 Jun  2 05:43 entrypoint
```
Making a fuse-overlay mount of this:
```
mkdir -p /tmp/X/{diff,work} /mnt/X
fuse-overlayfs -o lowerdir=/cvmfs/repo,upperdir=/tmp/X/diff,workdir=/tmp/X/work /mnt/X

ls -ld /mnt/X/entrypoint
drwxrwxrwx 2 root root 35 Jun  2 05:43 /mnt/X/entrypoint
```

If I try to touch a file: 
```
echo foo > /mnt/X/entrypoint/XXXXMJH
/mnt/X/entrpoint/XXXXMJH: Operation not permitted
```

(the above works as expected if all done as root)

If I recreate the overlay mount, this time adding at the top a layer on `/tmp` with `entrypoint/`, it works:
```
mkdir -p /tmp/layer/entrypoint
fuse-overlayfs -o lowerdir=/tmp/layer:/cvmfs/repo,upperdir=/tmp/X/diff,workdir=/tmp/X/work /mnt/X
```

OS is RHEL 8.6, tried latest version, 1.12 of `fuse-overlayfs`. 
Are you able to repro this? Do you understand what the issue is?

**Comment by DrDaveD** [comment]
For the record, what was the issue?
