### ISSUE TITLE
cvmfs crashes in posix quota

### ISSUE THREAD

**Issue by juztas** [cvmfs/cvmfs#3296]
Hi, I have a second node crashing on cvmfs and seems repeating. Crash log here: https://login-1.hep.caltech.edu/~jbalcas/cvmfs-crash
This node is a compute node (allocated for local users) and there was no jobs running during crash. The only thing this node does is periodically execute this:
```
singularity exec --home /wntmp/condor/:/srv --bind /storage/cms --bind /storage/af --bind /cvmfs --pwd /srv --contain --ipc --pid /cvmfs/singularity.opensciencegrid.org/cmssw/cms:rhel7 echo "Hello World" > /dev/null 2>&1
exitcode=$?
if test $exitcode -eq 0
then
    health_ok SINGULARITY
else
    health_fail SINGULARITY no_global_fail
fi
```
cvmfs version installed:
```
 yum list installed | grep cvmfs
cvmfs.x86_64                             2.10.1-1.2.osg36.el8                        @osg
cvmfs-config-osg.noarch                  2.5-2.osg36.el8                             @osg
cvmfs-x509-helper.x86_64                 2.2-2.osg36.el8                             @osg
```
Let me know if there is anything else I can provide or what the fix could be.

Thanks!

**Comment by HereThereBeDragons** [comment]
Hi
The error thrown stands for "No space left on device". Could you please double check that there is enough storage available?
If this is not the problem, you might be running out of file descriptors. Please double the value of  `CVMFS_NFILES` in your config and see if the problem occurs again.

Also for these kind of support questions please consider next time to use: https://cernvm-forum.cern.ch/ . We would prefer to have GitHub Issues only for bugs or improvement requests.

**Comment by HereThereBeDragons** [comment]
closing. please feel free to open it again if this issue reoccurs
