### ISSUE TITLE
Please update cvmfs-contrib-release to version 1.19

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3300]
Please update cvmfs-contrib-release-latest rpm and deb at http://ecsft.cern.ch/dist/cvmfs/cvmfs-contrib-release/ to the new tag v1.19 at https://github.com/cvmfs-contrib/cvmfs-contrib-release.  This adds support for el9, changes el8 to be based on AlmaLinux_8 instead of CentOS_8, removes Ubuntu 14.04 through 18.04 and Debian_9.0, and adds Ubnutu 22.04 and Debian 12.

**Comment by jblomer** [comment]
The new version is available

**Comment by DrDaveD** [comment]
I tried them both, they look good to me.  Please update the -latest copies as well.

**Comment by jblomer** [comment]
Thanks for checking! The latest links are now updated, too
