### ISSUE TITLE
Improve structure/filenames for integration tests

### ISSUE THREAD

**Issue by HereThereBeDragons** [cvmfs/cvmfs#3328]
We are running out of 3-digit numbers for client integration tests as tests are only considerred to be client tests if their name starts with `src/0*`

As there are also a lot of tests by now in a single folder, scrolling through them is quite exhausting.

There are multiple possible solutions:
1. Split tests in separate folders (client, server, gateway, ...)
2. Accept 4-digit numbers
3. Also declare 1** numbers as client tests

I personally would prefer option 1

**Comment by vvolkl** [comment]
> tests are only considerred to be client tests if their name starts with src/0*

I thought it was < 500? https://github.com/cvmfs/cvmfs/blob/devel/doc/developer/60-debugging-and-testing.md#writing-your-own-integration-tests (the container tools seem to have already reserved `4xx`, but still leaves a bit of space).

But in any case, we're approaching the number of tests where splitting it up seems  reasonable, +1

**Comment by HereThereBeDragons** [comment]
no the 500 is just the generall idea, not what th e scripts actually do. they check as shown above for `src/0*`. also the 400s are container tests.
