### ISSUE TITLE
macos client, post-FUSE - NSFileProviderReplicatedExtension

### ISSUE THREAD

**Issue by mj-harvey** [cvmfs/cvmfs#3363]
In case you've not seen this, the file provider API appears to be the closest thing to a userspace filesystem interface https://developer.apple.com/documentation/fileprovider/replicated_file_provider_extension
It would, hoewever, practically mean a complete replacement of the cvmfs fuse client.

Example of API use https://developer.apple.com/documentation/fileprovider/replicated_file_provider_extension/synchronizing_files_using_file_provider_extensions

**Comment by vvolkl** [comment]
Thanks, very interesting! This was new to me and we should certainly investigate this option.

**Comment by vvolkl** [comment]
The future on macos seems to FSKit, discussion here as well: https://github.com/cvmfs/cvmfs/issues/3620
