### ISSUE TITLE
New cvmfs 2.11 deb download, missing assoicated deb?

### ISSUE THREAD

**Issue by leeee-me** [cvmfs/cvmfs#3365]
The new apt release gpg key is failed to validate. Then I visited page at  https://cernvm.cern.ch/fs/
For Ubuntu 22.04, I downloaded these two deb files:

cvmfs_2.11.0 ~ 1 +ubuntu22.04_amd64.deb  
cvmfs-fuse3_2.11.0 ~ 1 +ubuntu22.04_amd64.deb

However, when installing via 'sudo dpkg -i', then it failed and asked for cvmfs-lib
Do you forget to add a new deb such as 

cvmfs-lib_2.11.0 ~ 1 +ubuntu22.04_amd64.deb?

**Comment by jeevadotnet** [comment]
Having the same issue on Ubuntu 22 LTS

**Comment by vvolkl** [comment]
@jeevadotnet @leeee-me The apt release key should now be fixed, please try again

The new release indeed added a dependency on `cvmfs-libs` for the `cvmfs` package, so you'll need to install this first when installing the .debs . The `cvmfs-libs` package is available under the same download url as the others, for example: 

http://ecsft.cern.ch/dist/cvmfs/cvmfs-2.11.0/cvmfs-libs_2.11.0~1+ubuntu22.04_amd64.deb

It was just missing from the website, I'll update it.
