### ISSUE TITLE
Question: Is Apache2 config suppose to be provided, because I don't see it ?

### ISSUE THREAD

**Issue by jeevadotnet** [cvmfs/cvmfs#3366]
OS: Ubuntu 20 / 22
New Install
Main repository

Good day

The documentation refers to "In general the cvmfs_server utility automatically manages the Apache configuration" ([link](https://cvmfs.readthedocs.io/en/stable/cpt-replica.html))

However I don't see any apache2 config being generated except the vanilla/default one, as when you install "apt-get install apache2". 

So my question is, is it suppose to generate on? Or do I need to DIY it? If so, can someone please provide me with an example because I'm struggling to get external/other servers to see the repo, however localhost works.

**Comment by vvolkl** [comment]
Hi @jeevadotnet , the link you are posting is for creating a replica ("stratum 1") of a repository. Is this what you are trying to do? If you want to create a new repository, you indeed don't need to touch any apache configuration. A good place to start is perhaps this tutorial: https://cvmfs-contrib.github.io/cvmfs-tutorial-2021/02_stratum0_client/

If you have further general questions ( as opposed to bug reports ) don't hestitate to ask; the CVMFS forum is a good place to post too: https://cernvm-forum.cern.ch

**Comment by jeevadotnet** [comment]
> 

Hi @vvolkl . Thanks for the feedaback, it is for Startum 0 (main repo), that doc just mentions that it will manage the Apache2 config. 

However, when I install "stratum 0" (cvmfs & cvmfs-server), it does install apache2, but there is no configuration. Even after starting a repo. /sites-available, etc only shows a default config. 

I'll blow away my testbed again, and try now again, but been doing that non stop for the last week.

**Comment by vvolkl** [comment]
The apache configuration is created when running `cvmfs_server mkfs <REPONAME>`, the location depends on the system, for RHEL based distributions it can be found under `/etc/httpd/conf.d/cvmfs.info.conf` and `/etc/httpd/conf.d/<REPONAME>.conf`

This is however not something you should need to change. Can you access `http://<PUBLISHERURL>/cvmfs/<REPONAME>/.cvmfspublished` from the client? Are your firewall rules allowing http access?

**Comment by jeevadotnet** [comment]
Great thanks wasn't aware of the forums will give it a go.

**Comment by vvolkl** [comment]
Hi @jeevadotnet,

It's expected that you only have the default config under `/etc/apache2/sites-enabled`, the stratum 0 is just a simple http server after all. Cvmfs-related config files should be under `/etc/apache2/conf-enabled/cvmfs*.conf`.

The error you get when running `cvmfs_server info` indicates an issue though. Can you attach the output of `cvmfs_config bugreport` here or in the forum?
