### ISSUE TITLE
Missing log messages on metadata download storage due to missing cache dirs

### ISSUE THREAD

**Issue by natefoo** [cvmfs/cvmfs#3370]
I've been debugging an issue with alien caches with unprivileged mounts on HPC systems and eventually figured out what I was doing wrong (`tmpwatch` as used to clean the alien cache was removing directories in addition to files, most notably, `txn`). However, debugging this was quite difficult, I eventually resorted to comparing `strace` output, because the `$CVMFS_DEBUGLOG` output does not indicate when a metadata file (`.cvmfspublished`, cert, catalog) download fails to be stored. See below for an examples of successful and failed mount attempts. Full logs are attached.

Both log download messages with no curl error, e.g.:

```
(download) escaped http://cvmfs1-iu0.galaxyproject.org/cvmfs/data.galaxyproject.org/data/1a/d02b17c788450377b304b4f7d51a59a0dc373fX to http://cvmfs1-iu0.galaxyproject.org/cvmfs/data.galaxyproject.org/data/1a/d02b17c788450377b304b4f7d51a59a0dc373fX    [08-22-2023 11:40:46 EDT]
(download) Verify downloaded url /data/1a/d02b17c788450377b304b4f7d51a59a0dc373fX, proxy DIRECT (curl error 0)    [08-22-2023 11:40:46 EDT]
(download) escaped http://cvmfs1-iu0.galaxyproject.org/cvmfs/data.galaxyproject.org/.cvmfswhitelist to http://cvmfs1-iu0.galaxyproject.org/cvmfs/data.galaxyproject.org/.cvmfswhitelist    [08-22-2023 11:40:46 EDT]
(download) Verify downloaded url /.cvmfswhitelist, proxy DIRECT (curl error 0)    [08-22-2023 11:40:46 EDT]
```

But in the missing `txn` case, these are not actually stored, but nothing is logged indicating as such. Both then move on to the file catalog. The failed mount logs:

```
(cache) miss /ocean/projects/mcb140028p/xcgalaxy/main/cvmfs_cache/6b/5af3e865b16cc919c7300f94eb091a568da9fc (-2)    [08-22-2023 11:40:46 EDT]
(cache) downloading file catalog at data.galaxyproject.org:/ (6b5af3e865b16cc919c7300f94eb091a568da9fc)    [08-22-2023 11:40:46 EDT]
(cache) could not start transaction on file catalog at data.galaxyproject.org:/ (6b5af3e865b16cc919c7300f94eb091a568da9fc)    [08-22-2023 11:40:46 EDT]
```

Whereas the successful mount logs:

```
(cache) miss /ocean/projects/mcb140028p/xcgalaxy/main/cvmfs_cache2/6b/5af3e865b16cc919c7300f94eb091a568da9fc (-2)    [08-22-2023 12:23:00 EDT]
(cache) downloading file catalog at data.galaxyproject.org:/ (6b5af3e865b16cc919c7300f94eb091a568da9fc)    [08-22-2023 12:23:00 EDT]
(cache) start transaction on /ocean/projects/mcb140028p/xcgalaxy/main/cvmfs_cache2/txn/fetchCIrXyb has result 21    [08-22-2023 12:23:00 EDT]
```

This reference to a `txn` path probably should have clued me in, but I unfortunately didn't catch it. Some additional logging around this would be super helpful.

[cvmfs_debug.success.log](https://github.com/cvmfs/cvmfs/files/12411396/cvmfs_debug.success.log)
[cvmfs_debug.failure.log](https://github.com/cvmfs/cvmfs/files/12411397/cvmfs_debug.failure.log)

**Comment by HereThereBeDragons** [comment]
Hi Nate
I had a look at your debug log. It is true that the debug log is a bit cryptic but you can extract from the failed mount log that it was unable to download the root catalog of the repo. below i have added some annotations to it.

i had a look adding more concrete logging messages in this particular case is a bit difficult as the different componenets know very little of each other. e.g. the download component just downloads a hash and does not know what exact file is behind it.

i of course understand your frustration and we try the best to have a good,  readable debug output. it benefits greatly any power user and the development process.

```bash
 # this is the hash of the latest root hash in the manifest (<repo>/.cvmfspublished).
# download of the manifest was successful. there will be an error if you cant download it (see manifest_fetch.cc +179  )
## this output should probably be changed to something better
(cache) remote checksum is 6b5af3e865b16cc919c7300f94eb091a568da9fc    [08-22-2023 11:40:46 EDT] 

# here it tries to find the root catalog (same hash as above)  in the cache but fails
(cache) miss /ocean/projects/mcb140028p/xcgalaxy/main/cvmfs_cache/6b/5af3e865b16cc919c7300f94eb091a568da9fc (-2)    [08-22-2023 11:40:46 EDT] 
# another cache look up that fails
(cache) miss /ocean/projects/mcb140028p/xcgalaxy/main/cvmfs_cache/6b/5af3e865b16cc919c7300f94eb091a568da9fc (-2)    [08-22-2023 11:40:46 EDT]

# try to download the root catalog
(cache) downloading file catalog at data.galaxyproject.org:/ (6b5af3e865b16cc919c7300f94eb091a568da9fc)    [08-22-2023 11:40:46 EDT] 
# next action planned fails because of reason listed below
(cache) could not start transaction on file catalog at data.galaxyproject.org:/ (6b5af3e865b16cc919c7300f94eb091a568da9fc)    [08-22-2023 11:40:46 EDT]
# could not download root catalog
(catalog) failed to load catalog '' (3 - failed to load catalog)    [08-22-2023 11:40:46 EDT] 
(catalog) failed to initialize root catalog    [08-22-2023 11:40:46 EDT]

# cleanup
(cache) unpinning / unloading all catalogs    [08-22-2023 11:40:46 EDT]
```

**Comment by natefoo** [comment]
Thanks for the annotations and for looking in to this! Once I figured out what the problem was, it did make the log messages easier to understand. I think the thing that would have made it much more obvious from the beginning is if there was a message indicating of the failure to open/write the temporary file in `txn`.

"`(catalog) failed to load catalog`" implied to me that the previous step of downloading had succeeded and that it was failing to read the downloaded catalog file, but that was not the case: downloading had failed, and "`(cache) could not start transaction`" was the cause, but *why* it could not start the transaction (which, I wasn't exactly sure what that referred to) was what escaped me.

Overall, CVMFS debug logging and architecture docs are great! So no complaints from me. Just thought this might help shed some light on this odd corner case.

**Comment by HereThereBeDragons** [comment]
Thanks for your message.
I will close this for now and we will try to improve the error messages where possible (the first confusing message should be changed by a currently open PR which does a lot of refactoring of the load catalog mechanism)
