### ISSUE TITLE
Bug: Attempting to mount non-existing repositories creates spurious directories in /cvmfs

### ISSUE THREAD

**Issue by vvolkl** [cvmfs/cvmfs#3401]
There are reports that the cvmfs 2.11 client will create directories in /cvmfs when doing a directory listing on non-existing repositories (for example with a typo). Currently live on lxplus7108:

```
* ********************************************************************
* Welcome to lxplus7108.cern.ch, CentOS Linux release 7.9.2009 (Core)
* Archive of news is available in /etc/motd-archive
* Reminder: you have agreed to the CERN
*   computing rules, in particular OC5. CERN implements
*   the measures necessary to ensure compliance.
*   https://cern.ch/ComputingRules
* Puppet environment: production, Roger state: production
* Foreman hostgroup: lxplus/nodes/login
* Availability zone: cern-geneva-c
* LXPLUS Public Login Service - http://lxplusdoc.web.cern.ch/
* An EL8 based lxplus8.cern.ch is now available
* An EL9 based lxplus9.cern.ch is now available
* Please read LXPLUS Privacy Notice in http://cern.ch/go/TpV7
* ********************************************************************
* 07-12-2023 - lxplus alias to switch to EL9 resources https://cern.ch/uefwc
~$ ls /cvmfs
alice.cern.ch                            etp.kit.edu
alice-nightlies.cern.ch                  faser.cern.ch
alice-ocdb.cern.ch                       fcc.cern.ch
ams.cern.ch                              fermilab.opensciencegrid.org
arm_neon.h                               ganga.cern.ch
atlas.cern.ch                            geant4.cern.ch
atlas-condb.cern.ch                      grid.cern.ch
atlas-nightlies.cern.ch                  ilc.desy.de
atlas-online-nightlies.cern.ch           larsoft.opensciencegrid.org
atlas-pixel-daq.cern.ch                  lhcb.cern.ch
BackendCommon.h                          lhcb-condb.cern.ch
beam-physics.cern.ch                     lhcbdev.cern.ch
cernvm-prod.cern.ch                      na61.cern.ch
clicdp.cern.ch                           na62.cern.ch
cms-bril.cern.ch                         nova.opensciencegrid.org
cms.cern.ch                              oasis.opensciencegrid.org
cms-ci.cern.ch                           opal.cern.ch
cms-ib.ce                                package.json
cms-ib.cer                               patatrack.cern.ch
cms-ib.cern                              process.h
cms-ib.cern.c                            projects.cern.ch
cms-ib.cern.ch                           RootDatabaseMerger.h
cms-opendata-conddb.cern.ch              sft.ce
compass.cern.ch                          sft.cern.c
compass-condb.cern.ch                    sft.cern.ch
compass-mc.cern.ch                       sft-nightlies.cern.ch
cpp.hint                                 ship.cern.ch
cpp.stop                                 singularity.opensciencegrid.org
cvmfs-config.cern.ch                     sndlhc.cern.ch
delphi.cern.ch                           sw.hsf.org
dstau.cern.ch                            sw-nightlies.hsf.org
dunedaq-development.opensciencegrid.org  unpacked.cern.ch
dunedaq.opensciencegrid.org              windows.h
dune.opensciencegrid.org
~$ 
``` 
The call to ls for the client will typically fail like this:
```
2023-09-22 15:54 ~$ ls -l /cvmfs/foo.bar.adsad
ls: cannot open directory /cvmfs/foo.bar.adsad: Too many levels of symbolic links
2023-09-22 15:54 ~$ ls -l /cvmfs/
total 10
drwxr-xr-x. 2 cvmfs cvmfs    0 Sep  4 13:11 clicdp.cern.ch
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 28  2014 cvmfs-config.cern.ch
drwxr-xr-x. 2 cvmfs cvmfs    0 Sep 13 11:12 foo.bar.aca
drwxr-xr-x. 2 cvmfs cvmfs    0 Sep 22 15:54 foo.bar.adsad
```
but then still create the directory entry, which cannot be read:
```
~$ ls /cvmfs/sft.cern.c
ls: cannot open directory /cvmfs/sft.cern.c: No such file or directory
```
A debuglog from one of the affected machines is here: 
[cvmfs_debug(2).log](https://github.com/cvmfs/cvmfs/files/12712536/cvmfs_debug.2.log)

**Comment by DrDaveD** [comment]
I don't see how this can have anything to do with the cvmfs client.  It's much more likely the el9 automounter.

Beyond that, it's something peculiar about the lxplus el9 configuration, because I have an el9 VM at CERN that does not show this behavior.  In the past the "Too many levels of symbolic links" error has been seen most frequently inside containers when the mount namespace is not fully shared back with the host, for example with docker `-v` volume mount without the `:shared` option.

**Comment by vvolkl** [comment]
No, we've seen this behavior across platforms. The lxplus machine above is el7, and I can also reproduce it with my ubuntu desktop. It's possible that  we return a wrong return code in the mount helper, but it's also flaky, so  not immediately clear yet.

**Comment by DrDaveD** [comment]
Ok then it's something peculiar to all the lxplus configuration and coincidentally on your ubuntu desktop.  I tried it on a vagrant ubuntu 22.04 VM and it didn't happen for me. 

For example lxplus puts each user into a separate pid namespace, because if you do ps -ef you only see your own processes, using the [hidepid](https://www.cyberciti.biz/faq/linux-hide-processes-from-other-users/) option when mounting /proc.  It might be that or some other peculiar configuration they have done, it's hard to know what is running on that machine because of that trick they used.

I can reproduce the leftover mountpoint on an lxplus el7 machine although I don't see "Too many levels of symbolic links".

**Comment by DrDaveD** [comment]
I tried enabling `hidepid=1` on my ubuntu 22.04 VM and got it to hide other processes but it did not cause an invalid access in /cvmfs to leave a directory behind.

**Comment by HereThereBeDragons** [comment]
I could spuradically recreate it on my ubuntu 22.0 laptop.
The folders could be created either with error
```
Too many levels of symbolic links
```
or
```
No such file or directory
```

contrary to the lxplus node, on my system it would eventually clean up this wrongly created directories (I saw this only when asking to access a new non-existing directory). I am not sure if this is because the console already had sudo rights (I ran with local non-root user, but had already entered the root password before wouldnt have to verify again)

**Comment by HereThereBeDragons** [comment]
It might be also related to this:
```
> ls /cvmfs/
ls: cannot access '/cvmfs/just.test.repo': Too many levels of symbolic links
ls: cannot access '/cvmfs/test.repo.org': No such file or directory
ls: cannot access '/cvmfs/my.test.repo': No such file or directory
just.test.repo  my.test.repo  test.repo.org

> ls /cvmfs/
ls: cannot access '/cvmfs/just.test.repo': Too many levels of symbolic links
cvmfs-config.cern.ch  just.test.repo

> ls /cvmfs/
ls: cannot access '/cvmfs/just.test.repo': No such file or directory
cvmfs-config.cern.ch  just.test.repo

# this is the only healthy one
 > ls /cvmfs/
cvmfs-config.cern.ch
```
Note: These are all valid repos but with outdated whitelists. Accessing `ls /cvmfs` when these broken repos are returned takes a couple of seconds, instead of instant access when just valid repos are returned:

**Comment by DrDaveD** [comment]
It's normal for invalid repositories to take a while, because it has to check all the stratum 1s in case a repository isn't hosted on some of them.

On which type of host do you see `Too many levels of symbolic links`?  I don't see it on lxplus el7, and yet it still remembers the invalid reference in /cvmfs.  It may be two independent issues.

**Comment by HereThereBeDragons** [comment]
this was now my ubuntu machine. valentin first show it to me on an lxplus el7 node

here some more output of my ubuntu laptop creating fake repos (seems to be easier with valid file endings):
```bash
$ ls /cvmfs/file.cpp
ls: cannot access '/cvmfs/file.cpp': Too many levels of symbolic links

$ ls /cvmfs/
ls: cannot access '/cvmfs/file.cpp': Too many levels of symbolic links
cvmfs-config.cern.ch  file.cpp

$ ls /cvmfs/file.h
ls: cannot access '/cvmfs/file.h': Too many levels of symbolic links

$ ls /cvmfs/
ls: cannot access '/cvmfs/file.h': Too many levels of symbolic links
ls: cannot access '/cvmfs/file.cpp': Too many levels of symbolic links
cvmfs-config.cern.ch  file.cpp  file.h
```

**Comment by DrDaveD** [comment]
Which Ubuntu version?  Is there anything unusual about the environment that you're running under?

**Comment by HereThereBeDragons** [comment]
No nothing special, just my development environemnt. but as i said we also have seen this on some lxplus el7 nodes

**Comment by DrDaveD** [comment]
You haven't seen the `Too many levels of symbolic links` issue on lxplus, that's the issue that I'm concerned about.  Which version of Ubuntu?

**Comment by HereThereBeDragons** [comment]
Im pretty sure we saw both versions on lxplus: `Too many levels of symbolic links` and `No such file or directory` to create non-existing repos.
but its ubuntu 22

**Comment by DrDaveD** [comment]
So it doesn't happen when I try it under ubuntu22.04 under vagrant.  What might be different between your ubuntu 22.04 desktop environment and a standard vagrant VM?  It has autofs version 5.1.8-1ubuntu1.3 and cvmfs version 2.11.0~1+ubuntu22.0?

**Comment by HereThereBeDragons** [comment]
It is a very flaky behavior. Before it was mentioned to me I also never saw it. I have the impression that it is easier to trigger this unwanted behavior if you use stnadard file endings.
My ubuntu 22 contrary to the lxplus el7 node also cleans up those broken repos after time as shown in the logs above.

**Comment by smuzaffar** [comment]
Hi,
  On lxplus8 node I see some strange directories under /cvmfs e.g. on lxplus805 I get "/cvmfs/cms-ib.c" and "/cvmfs/cms-ib.cern.ch" [a]. On lxplus785/lxplus735 (may be other too) I see vary strange repos under /cvmfs [b] (looks like some Geant4 files are shown as cvmfs repositories ). Although this does not break any thing but it looks odd and no idea how these are created. Just reporting here so that someone can look in to it.

Cheers,
--Shahzad

[a] lxplus8
```
[muzaffar@lxplus805 xx]$ ls -ld /cvmfs/cms-ib.c*
drwxr-xr-x. 2 cvmfs cvmfs 0 Oct  5 20:06 /cvmfs/cms-ib.c
drwxr-xr-x. 2 cvmfs cvmfs 0 Oct  4 17:57 /cvmfs/cms-ib.cern.ch
```
[b] lxplus (CC7)
```
[muzaffar@lxplus785 muzaffar]$ ls /cvmfs/
BackendCommon.h                 ams.cern.ch                     cms-ib.cern.ch                larsoft.opensciencegrid.org  sft-nightlies.cern.ch
BaseTsd.h                       arm_neon.h                      cms.cern.ch                   lhcb-condb.cern.ch           sft.cern.ch
G4MTAdjointSimManager.hh        atlas-condb.cern.ch             cvmfs-config.cern.ch          lhcb.cern.ch                 singularity.opensciencegrid.org
G4ShellCorrections.hh           atlas-nightlies.cern.ch         direct.h                      lhcbdev.cern.ch              sndlhc.cern.ch
G4UIExecutive.hh                atlas-online-nightlies.cern.ch  dune.opensciencegrid.org      na61.cern.ch                 sw-nightlies.hsf.org
G4VFastSimSensitiveDetector.hh  atlas.cern.ch                   fermilab.opensciencegrid.org  na62.cern.ch                 sw-nightlies.sw
TRandom.h                       cbdfls.h                        ganga.cern.ch                 opal.cern.ch                 sw.hsf.org
TargetConditionals.h            cernvm-prod.cern.ch             geant4.cern.ch                patatrack.cern.ch            unixio.h
alice-ocdb.cern.ch              clicdp.cern.ch                  grid.cern.ch                  process.h                    unpacked.cern.ch
alice.cern.ch                   cms-bril.cern.ch                ilc.desy.de                   projects.cern.ch             windows.h
alloc.h                         cms-ci.cern.ch                  io.h                          qgl.h
[muzaffar@lxplus785 muzaffar]$ file /cvmfs/BaseTsd.h
/cvmfs/BaseTsd.h: directory
[muzaffar@lxplus785 muzaffar]$ cd /cvmfs/BaseTsd.h
-bash: cd: /cvmfs/BaseTsd.h: No such file or directory
```

**Comment by DrDaveD** [comment]
@smuzaffar I think that's exactly what the issue is about; I don't think you are saying anything new except that I guess nobody mentioned lxplus8 before.  So it applies on all the lxplus nodes.

**Comment by DrDaveD** [comment]
Oh I just noticed that lxplus machines are not running the automount daemon.  They must be using some other mechanism for automount.  Does anybody know what it is?  I wonder if it is the same method as used on @HereThereBeDragons's ubuntu.

**Comment by jblomer** [comment]
They may be running systemd automount units?  Are you sure the automounter is not running? When logging in as a normal user, one is now in a PID sandbox.

**Comment by DrDaveD** [comment]
Oh that's a good point, I forgot about the sandbox.  automount may indeed be running but hidden from me.

**Comment by vvolkl** [comment]
This problem is due to a race condition introduced in https://github.com/cvmfs/cvmfs/pull/3144 , which explains why it was difficult to reproduce: Under certain circumstances the mount helper returns success without waiting  for the true exit code of the cvmfs2 process, throwing autofs in a loop, calling the mount helper again and again. If this goes on for long enough, autofs gives an error, typically "Too many levels of symbolic links", without cleaning up the directory. Fixed in the linked PR, we'll still include this in 2.11.2.
