### ISSUE TITLE
YubiKey 5 Nano not recognized by `cvmfs_server masterkeycard`

### ISSUE THREAD

**Issue by bedroge** [cvmfs/cvmfs#3437]
I'm trying to use a YubiKey 5 Nano with `cvmfs_server masterkeycard`, but this doesn't seem to work:
```
$ cvmfs_server masterkeycard -a
opensc-tool -l has no device matching "Yubikey.*CCID"
```

Looking at the output of `opensc-tool -l`, it's actually due to the uppercase `K` in `YubiKey` for my device:
```
$ opensc-tool -l
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    No              Broadcom Corp 58200 [Contacted SmartCard] (0123456789ABCD) 00 00
1    Yes             Yubico YubiKey OTP+FIDO+CCID 01 00
```

Perhaps this was changed for newer YubiKey devices? Would it be possible to change the pattern that's being used in `cvmfs_server` to something like `"Yubi[kK]ey.*CCID"`? That seems to fix the issue for me:
```
$ ./cvmfs_server masterkeycard -a
masterkeycard is available
```

**Comment by DrDaveD** [comment]
It's certainly possible, as you found!  Could you submit a pull request?
