### ISSUE TITLE
`cvmfs_server masterkeycard -c` fails on `openssl pkeyutl` command

### ISSUE THREAD

**Issue by bedroge** [cvmfs/cvmfs#3439]
I'm trying to move a masterkey to my Yubikey device following the instructions from https://cvmfs.readthedocs.io/en/stable/cpt-repo.html#master-keys, but I keep getting the following error:

```
$ sudo cvmfs_server masterkeycard -s test.eessi.io
Successfully imported a new private key.
Successfully imported a new certificate.

Now back up /etc/cvmfs/keys/test.eessi.io.masterkey
to flash drives stored in safe places and use
  cvmfs_server masterkeycard -c test.eessi.io
to remove the masterkey and convert to use the key in the card.

$ sudo cvmfs_server masterkeycard -c test.eessi.io
The following repository(ies) will be converted to use the masterkeycard:
  test.eessi.io
This will remove the masterkey and update the pub key and cannot be undone!
Are you sure you want to proceed (y/N)? y
Removing /etc/cvmfs/keys/test.eessi.io.masterkey and updating pub key
Signing 7 day whitelist with masterkeycard... invalid masterkeycard signature
```

I've added some debugging commands to `/usr/bin/cvmfs_server`, and it turns out that the `openssl` command is failing:
```
openssl pkeyutl -verify -inkey /var/spool/cvmfs/test.eessi.io/tmp/whitelist.test.eessi.io.pub -pubin -in /var/spool/cvmfs/test.eessi.io/tmp/whitelist.test.eessi.io.signature
pkeyutl: No signature file specified for verify
invalid masterkeycard signature
```
This is with version `OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)`, and it looks like it's expecting some more/other arguments (`-sigfile` perhaps?)? I've also tried disabling the check for OpenSSL 3 in the code, which makes it use `openssl rsautl` instead of `openssl pkeyutl`, and that does seem to work fine (though it's printing a deprecation message).

**Comment by bedroge** [comment]
Should it perhaps do something like `openssl pkeyutl -verify -inkey ${whitelist}.pub -pubin -in ${whitelist}.hash -sigfile ${whitelist}.signature`?

**Comment by vvolkl** [comment]
Hi Bob,

thanks for the report! We currently only support and test Yubikey 4  (as mentioned in the docs) -  I think that to properly support Yubikey 5 we'd need to get the hardware to test it, which should not be impossible. In the meantime I cannot comment on this issue, but I'm happy to accept patches that pass the tests, in particular https://github.com/cvmfs/cvmfs/blob/devel/test/src/643-masterkeycard/main

**Comment by bedroge** [comment]
Hi Valentin, I completely understand that, but I had the feeling that this wasn't related to the device itself. By removing the check for OpenSSL 3 (here: https://github.com/cvmfs/cvmfs/blob/cvmfs-2.11.2/cvmfs/server/cvmfs_server_ssl.sh#L67) and using the old (deprecated) function from earlier versions things seem to work correctly. So, for me that seemed like an indication that there's actually something wrong with the command that's being used for OpenSSL 3.

**Comment by bedroge** [comment]
I also just tested this by pointing `cvmfs_server` to a container that has OpenSSL 1.1.1, and then it works fine as well. 

I'm happy to provide a patch for the issue, but I'm not really sure what [this piece of code](https://github.com/cvmfs/cvmfs/blob/cvmfs-2.11.2/cvmfs/server/cvmfs_server_ssl.sh#L120) is supposed to do. Since it involves the integrity/security of the repo, I'd rather be sure what I'm doing. But my guess is that we have to provide the signature as `-sigfile`, and then use the `${whitelist}.hash` for `-in`? I just tried that interactively by dumping all those files to a directory, and at least the command then does not complain anymore:

```
$ openssl pkeyutl -verify -inkey ./whitelist.test.eessi.io.pub -pubin -sigfile ./whitelist.test.eessi.io.signature -in ./whitelist.test.eessi.io.hash
Signature Verified Successfully
```

If someone could confirm that this is the right command, I'd be happy to make a PR.

**Comment by DrDaveD** [comment]
The existing command in the script is
```
openssl_keyutil_cmd} -verify -inkey ${whitelist}.pub -pubin -in ${whitelist}.signature
```
Is it enough to just replace the `-in` with `-signature`, without adding the hash?  And does the same command work with both openssl1.1.1 and openssl3?

**Comment by bedroge** [comment]
```
$ openssl pkeyutl -verify -inkey ./whitelist.test.eessi.io.pub -pubin -sigfile ./whitelist.test.eessi.io.hash
```
This doesn't work: nothing happens, and it seems it's expecting some input.

```
$ openssl pkeyutl -verify -inkey ./whitelist.test.eessi.io.pub -pubin -in ./whitelist.test.eessi.io.hash -sigfile ./whitelist.test.eessi.io.signature
```
This works for both OpenSSL 1 and 3.

**Comment by DrDaveD** [comment]
Ok then it must be right.
