### ISSUE TITLE
Error: character device /dev/fuse does not exist

### ISSUE THREAD

**Issue by julianmorillo** [cvmfs/cvmfs#3463]
After installing a cvmfs client (built from source in a Fedora 37 RISC-V system), I'm getting this error:
```
$ sudo cvmfs_config chksetup
Error: character device /dev/fuse does not exist
```
Who/which command is in charge of creating this device? Do you have a clue on what the problem could be or what else can I check to have more information?

Thanks.

**Comment by vvolkl** [comment]
This should be provided by the fuse package. Since you are building from source, you'll need to install build and runtime dependencies by hand, in particular 

```
dnf -y install attr fuse3 autofs httpd
```

**Comment by DrDaveD** [comment]
I don't think that's a correct answer.  /dev/fuse is a kernel construct, and fuse3 is an optional user-level package.  If it's any user-level package it would be fuse3-libs, which is a dependency of fuse3.

I just booted up a new fedora37 vagrant vm from scratch, and it already had /dev/fuse.  It had fuse-libs installed, but `rpm -qf /dev/fuse` said it wasn't owned by any package.  It's more likely a kernel configuration.

**Comment by jblomer** [comment]
It may be that `modprobe fuse` is missing to load the fuse kernel module.

**Comment by DrDaveD** [comment]
> It may be that `modprobe fuse` is missing to load the fuse kernel module.

Exactly.  That can be checked with `lsmod | grep fuse`.   I'm not sure exactly where the default list comes from but [Fedora documentation](https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/kernel-module-driver-configuration/Working_with_Kernel_Modules/) shows how to load additional modules at boot time.

**Comment by DrDaveD** [comment]
As an experiment, I added
```
blacklist fuse
```
to /etc/modprobe.d/fuse-blacklist.conf and rebooted my generic/fedora37 vagrant VM.  It did come up without the `fuse` module loaded, but it still created /dev/fuse.  So I'm not sure how to even prevent that.

**Comment by vvolkl** [comment]
@julianmorillo Did you ever figure out why you were missing the fuse device? I'm closing this issue as it is not a cvmfs issue, but do let us know.

**Comment by julianmorillo** [comment]
@vvolkl It was missing because FUSE was not installed. If I remember correctly, I installed FUSE and loaded the kernel module. Everything is working now, thanks for the support.
