### ISSUE TITLE
Creating new repository fails when using MinIO as S3 provider

### ISSUE THREAD

**Issue by maxnoe** [cvmfs/cvmfs#3484]
I am trying to get a working setup of a cvmfs server in docker (we'd like to spin-up a fresh cvmfs instance in our CI for integration tests).

Using local storage, I ran into a brick wall due to systemd and apache being hard requirements for that and that not working in docker.

So I tried using MinIO as an S3 provider, which seems to work nicely -- up to some point.

When creating the repository, everything goes fine and files are created in the S3 endpoint until something tries to get the S3 URL without the bucket name it seems:

```
Creating bucket
Bucket 's3://cvmfs/' created
Creating Configuration Files... done
Creating CernVM-FS Master Key and Self-Signed Certificate... done
Creating CernVM-FS Server Infrastructure... done
Signing 30 day whitelist with master key... done
Creating Initial Repository... HTTP protocol error 403: http://cvmfs-storage:9000/ctao.dpps.test/.cvmfsreflog (9)
failed loading reflog (3 - network failure)
reflog missing
fail! (cannot sign repo)
```

This is my s3 config for cvmfs:

```
CVMFS_S3_ACCESS_KEY=root
CVMFS_S3_SECRET_KEY=top-secret
CVMFS_S3_HOST=cvmfs-storage
CVMFS_S3_PORT=9000
CVMFS_S3_BUCKET=cvmfs
CVMFS_S3_USE_HTTPS=false
CVMFS_S3_DNS_BUCKETS=false
```

After the failed command, I see the following files:

```
[root@ebaf819a692d /]# s3cmd ls s3://cvmfs/ctao.dpps.test/
                          DIR  s3://cvmfs/ctao.dpps.test/data/
2024-01-16 17:38         5120  s3://cvmfs/ctao.dpps.test/.cvmfsreflog
2024-01-16 17:38          407  s3://cvmfs/ctao.dpps.test/.cvmfswhitelist
```

**Comment by vvolkl** [comment]
Hi @maxnoe, can you share as well the `mkfs` command you used here? I'm not an expert with regards  to using S3 backends, but I think it is required to have http access, so you should try if you can curl http://cvmfs-storage:9000/ctao.dpps.test/.cvmfsreflog directly and fix any access issues there.

Furthermore, I'm also not 100% sure about this but when using docker you may run into problems with overlayfs ( which is required for normal publications) - typically publisher machines are bare metal or vm instances.

**Comment by maxnoe** [comment]
Sorry for the less than full issue report, I was in a hurry yesterday evening leaving the office.
I now pushed my full docker-compose setup here: https://github.com/maxnoe/cvmfs-server-docker.

Running `docker compose up` in that repo should exactly reproduce the issue and you can see the commands in the `entrypoins.sh` file. The two config files (for s3cmd and s3 config for cvmfs server are also there.)

> Furthermore, I'm also not 100% sure about this but when using docker you may run into problems with overlayfs ( which is required for normal publications) - typically publisher machines are bare metal or vm instances.

This is a bit of an exercise to see if it's possible to dockerize cvmfs... there were some attempts before which seemed to work: https://github.com/gabrielefronze/cvmfs-server-container

but these were using the soon-to-be-EOL centos 7, so I wanted to try again.


> if you can `curl http://cvmfs-storage:9000/ctao.dpps.test/.cvmfsreflog` 

The issue is that the bucket here is missing, the URL should be:

`http://cvmfs-storage:9000/cvmfs/ctao.dpps.test/.cvmfsreflog`

note the additional `cvmfs`, which is the S3 bucket I configured (and that was apparently correctly used by at least some parts of the codebase, since files were uploaded to that location.

**Comment by vvolkl** [comment]
Can you try: 
```diff
--w http://cvmfs-storage:9000/ \
+-w http://cvmfs-storage:9000/cvmfs \
```
at
https://github.com/maxnoe/cvmfs-server-docker/blob/main/entrypoint.sh#L13
?

**Comment by maxnoe** [comment]
After setting anonymous read access, that works.

However, running into more problems then related to docker. However, since that fixed the issue here, I am closing.

Would it make sense to open another general issue for support of running cvmfs_server in docker? Or was this already discussed as a non-goal?

**Comment by vvolkl** [comment]
OK! Feel free to open another issue, also a general one for dockerized publishers. I don't know if it was previously discussed, we'll have to discuss it again internally.
