### ISSUE TITLE
cvmfs_getxattr assert()

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3515]
Seeing a rare crash at this `assert()`:

https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1754

Pending a proper fix of this, we should demote this to `AssertOrLog()` as at https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1766

I do have a core file of this crash, if anything from that would be of use in root-causing.

This isn't a new bug, it's going to have been present since 2.8.1

**Comment by HereThereBeDragons** [comment]
it seems like  this code section 

https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1783-L1788

should be move above the `assert`

https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1747-L1755

then it would be good to know if the `assert` is still triggered

**Comment by mharvey-jt** [comment]
Also seeing an assert from 

https://github.com/cvmfs/cvmfs/blob/9fc9c4015f6f3fcc98c9cec1f48fdb77003a034f/cvmfs/cvmfs.cc#L1755-L1762

seems like the reasonable behaviour here is to fall through?

**Comment by HereThereBeDragons** [comment]
PR #3516 should have solved the issue
