### ISSUE TITLE
New MaxMind API for geoIP downloads

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3529]
Maxmind has again [changed the API for geoIP database downloads](https://dev.maxmind.com/geoip/release-notes/2024#presigned-urls-for-database-downloads), and the old one will stop working May 1.   `cvmfs_server` needs to be updated to use the new API.

**Comment by DrDaveD** [comment]
@cvuosalo found that new license keys are already requiring a `-L` option added to curl to respond to a redirect request.  Old license keys don't require that.   This means that anybody trying to set up a geodb with a new account between now and when this issue is fixed will need to manually hack the curl command in cvmfs_server.

**Comment by vvolkl** [comment]
@DrDaveD We also see an issue with geodb in our integration tests. Do you have a fix already or should we take a look? I'm happy to do a patch release soon after this is fixed.

**Comment by cvuosalo** [comment]
@vvolkl We have a fix in mind, but it will take a few work days to complete.

**Comment by DrDaveD** [comment]
What issue do you see?  A temporary workaround might be to add the `-L` option to the curl line, if it's the same problem that Carl saw with a new license key.

**Comment by jblomer** [comment]
There is now a rate limit that we hit.

**Comment by DrDaveD** [comment]
Ah.  I think there has been a rate limit for quite some time, but maybe they reduced the limit.

**Comment by cvuosalo** [comment]
PR #3566  addressing this issue has been merged. I think this issue can be closed.
