### ISSUE TITLE
Update cvmfs-contrib-release to version 1.20

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3550]
Please update the cvmfs-contrib-release-latest rpm and deb at http://ecsft.cern.ch/dist/cvmfs/cvmfs-contrib-release/ to the new tag v1.20 at https://github.com/cvmfs-contrib/cvmfs-contrib-release. This replaces the gpg signing key due to expire in 2 months and adds Ubnutu 24.04.

**Comment by vvolkl** [comment]
Done, they're available under http://ecsft.cern.ch/dist/cvmfs/cvmfs-contrib-release/ . Can you double-check and let me know if they look good? Then I'll also update the "latest" symlink.

**Comment by DrDaveD** [comment]
They look good, thanks.

**Comment by vvolkl** [comment]
Updated the latest symlink as well.
