### ISSUE TITLE
receiver inefficiency: ShortString wrangling

### ISSUE THREAD

**Issue by mharvey-jt** [cvmfs/cvmfs#3568]
Looking at the grafting of a particularly large catalog we have, containing 44k+ nested catalogs, no files, and full path lengthd  of ~ 34 chars, I see that 70%+ of runtime is in these four lines:
https://github.com/cvmfs/cvmfs/blob/47a223e1e0398d8b32ecab091c5b1155cd78540c/cvmfs/catalog_diff_tool_impl.h#L147-L150

From a perf:
```
   33.42%    33.42%  cvmfs_receiver  cvmfs_receiver                     [.] ShortString<(unsigned char)200, (char)0>::GetLength                                                                        
+   28.46%    28.46%  cvmfs_receiver  libc-2.28.so                       [.] __memcmp_avx2_movbe                                                                                                        
+   11.77%    11.77%  cvmfs_receiver  cvmfs_receiver                     [.] ShortString<(unsigned char)200, (char)0>::StartsWith      
```
we've already had one pass at optimising these, which introduced Truncate(). Anything else we can do to further improve things here? It might require a structural change in `DiffRec` rather than a micro-optimisation of GetLength(), StartsWith(). One possibility would be computing `old_path`, `new_path` only when required, rather than on every iteration.

I've confirmed that the PathStrings never go into the the long_string_ path.

**Comment by jblomer** [comment]
Does this turned out to be no longer an issue?

**Comment by mharvey-jt** [comment]
Yes - I was misreading the perf report. The bulk of the runtime turned out to be in LookupXattrs(), per https://github.com/cvmfs/cvmfs/issues/3569
