### ISSUE TITLE
Small bug in cvmfs/externals/ipaddress/ipaddress-1.0.22.tar.gz

### ISSUE THREAD

**Issue by cvuosalo** [cvmfs/cvmfs#3599]
`ipaddress.py` from `cvmfs/externals/ipaddress/ipaddress-1.0.22.tar.gz` has a small bug. Line 1106 has:
```
raise TypeError("%s and %s are not of the same version" (a, b))
```
but it should be:
```
raise TypeError("%s and %s are not of the same version"  % (a, b))
```
This bug causes a Python error when the line is executed.

Should the script in the tar archive be fixed? In which case, what version number should be used for the tar archive?

On the other hand, there is a newer version of `ipaddress` available here:
https://pypi.org/project/ipaddress/#description
The latest is 1.0.23, which does fix this bug. However, it has other changes and enhancements, which might cause unexpected and undesired effects.
How should this bug be fixed?

**Comment by vvolkl** [comment]
Hi Carl, 

thanks for the report! In general,  to fix this bug in the current version, the best way is to keep the tarball as is and add a patch - there are examples in other external packages and the bootstrap.sh script.

Updating is usually a good option if a newer version is possible, and I think our testing suite should be comprehensive enough to catch side effects. Looking at this library, it seems that it is really just a backport of a feature of the standard library in python 3.3+. I'd be happy to drop python2 support in CVMFS, I don't think there are any platforms any more that don't have python3. Maybe the best option is to remove this library altogether?

**Comment by DrDaveD** [comment]
That seems reasonable to me
