### ISSUE TITLE
Incorrect number of seconds in a day

### ISSUE THREAD

**Issue by Pikamander2** [cvmfs/cvmfs#3600]
Hi there, I used a code search and found an incorrect number of seconds in a day (84600 instead of 86400) listed in one of your files. I recommend fixing it to avoid incorrect timings that could potentially lead to unexpected behavior.

https://github.com/cvmfs/cvmfs/blob/18af0436a16a12ad0f022bed1dbe400970208679/cvmfs/network/dns.h#L182

**Comment by vvolkl** [comment]
Hi, thanks for reporting this issue! In this case, the constant was mostly used as an arbitrary "long time", so fortunately I wouldn't expect any serious consequences, but I'll fix it, it'll be good to fix to avoid surprises!
