### ISSUE TITLE
package cvmfs-2.11.2 in yum repo was truncated

### ISSUE THREAD

**Issue by sabo** [cvmfs/cvmfs#3605]
Hello,
version 2.11.2 of the cvmfs RPM package in the cernvm repo appears to have been replaced with a truncated version when 2.11.3 was uploaded. GPG signature checks fail, and the package itself is around 4MB when all other versions of CVMFS are around 14-15MB.

**Comment by vvolkl** [comment]
I think that's exactly what happened - thanks for letting us know! This should now be fixed, please try again.

**Comment by sabo** [comment]
looks good to me, thanks!
