### ISSUE TITLE
ATLAS/US ATLAS client issues

### ISSUE THREAD

**Issue by deesto** [cvmfs/cvmfs#3615]
We need to better centralize the months-long efforts at multiple sites for chasing down and identifying CVMFS client issues, some triggered by ATLAS pilot and wrapper checks on repositories necessary for running ATLAS jobs, others identified by sites independently or using monitoring tools. Github seems the best place to coordinate this activity, and I've been asked to create this issue.

On the US side, Fred has created [this document](https://docs.google.com/document/d/1MhO9dNmylBQPmN2-c0PBYdX_8B2dk8Na1CJ_HbSYPVI/), which contains details of several client instances that should be looked at in order to gain an understanding of the full scope of these issues.

One related Github issue [here](https://github.com/cvmfs/cvmfs/issues/3611) details an issue that Dave, Jakob, and Valentin have examined with client mounts getting stuck and unable to re-mount, with a proposed fix [here](https://github.com/cvmfs/cvmfs/pull/3614).

**Comment by deesto** [comment]
[One GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=166868) on the US Cloud and the BNL site for issues found by ATLAS jobs with the client, on three separate dates. Follow-ups on the nodes cited with issues found no problems on any of the three dates.

**Comment by deesto** [comment]
[An ATLAS Jira ticket](https://its.cern.ch/jira/browse/ATLASPANDA-998) summarizing a discussion with Paul and Asoka on the ATLAS pilot checks and improvements (timeouts, repos to be checked).

**Comment by deesto** [comment]
[A newly reopened GGUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=167051) today on failed pilots at NET2 (30k in 12h). The prominent error is:
`/bin/bash: /cvmfs/atlas.cern.ch/repo/sw/PandaPilotWrapper/latest/runpilot2-wrapper.sh: Transport endpoint is not connected`

**Comment by mlassnig** [comment]
Hi, any news on this?

**Comment by vvolkl** [comment]
Hi Mario,
we've identified one actual CVMFS issue referenced by John above where we do not recover properly from a cache manager crash - the crash itself is likely an issue with the site cache configuration. But I guess you are referring to the latest ticket posted by @deesto? In that case I cannot comment, we don't have access to GGUS tickets.

**Comment by deesto** [comment]
@vvolkl I attach here the exports of the two aforementioned GGUS tickets (in beautiful XML format -- and I had to ZIP them as GitHub does not accept XML files -- sorry)
[cvmfs_ggus.zip](https://github.com/user-attachments/files/15971961/cvmfs_ggus.zip)
I've summarized the BNL ticket above; at NET2, Eduardo is fighting through recurring issues with the CVMFS daemonset in a k8s deployment.

**Comment by deesto** [comment]
And now seeing how useless those XML exports are, I'll just copy a few bits from the NET2 ticket:
> There are about 30K failed pilots in 24 hours, and only 15K finished. 
Link to os-atlas dashboard:
https://os-atlas.cern.ch/dashboards/goto/420eab5454aa01949d8f036ffa4682aa?security_tenant=global
Example of log output: 
https://aipanda117.cern.ch:25443/cache/CERN_central_k8s_al9_5046779.out
`/bin/bash: /cvmfs/atlas.cern.ch/repo/sw/PandaPilotWrapper/latest/runpilot2-wrapper.sh: Transport endpoint is not connected`

> 11K failed pilots in the past 12 hours with the same type of error as before: 
...
Link to os-atlas dashboard:
https://os-atlas.cern.ch/dashboards/goto/ced61429a3ced0242b651b74dbbfdfdf?security_tenant=global

**Comment by deesto** [comment]
There is an email conversation going with AGLT2, which have experienced many I/O errors and hung mounts. My crude summary of Valentin's diagnosis is that there is that their client cache partition is too small, and normal cache clean-up fails to wipe files pinned by long running processes, so the partition fills. Recommendations there are to isolate the cache partitions, and increase partition size of the shared cache so that the cache quota size (which is deliberately less than the partition size) can handle the typical number and size of requested files.

**Comment by HereThereBeDragons** [comment]
hallo

deesto is right, that was our last idea.

i also had a look at all your tickets etc. and sadly there was not enough information related to help cvmfs debugging. we only came to this conclusion because valentin at that time had direct access to one of the nodes.

next time if issues like this occur, it would be highly appreciated if you could use `sudo cvmfs_config bugreport` ( https://cvmfs.readthedocs.io/en/stable/apx-contact.html#contact-information ) to create a tarball on the broken node. this tarball will contain a lot of helpful information to more easily find such problems.

thanks,
laura

**Comment by deesto** [comment]
Thanks @HereThereBeDragons. We also found in that case via email that the site very likely has disk and quota set that are not fully compatible with ATLAS grid work (since ATLAS jobs require much more than just the ATLAS repo alone), and hopefully our recommendations to increase those will help. But this was only one of several sites with recurring and ongoing issues, all of which we're trying to corral here. There's still more to look into and do, e.g., [the NET2 issue](https://github.com/cvmfs/cvmfs/issues/3615#issuecomment-2188996175).

**Comment by deesto** [comment]
Just opened a new issue for a "black hole" ATLAS WN at BNL caused by CVMFS client hangs on an EL9 (Alma) node:
https://github.com/cvmfs/cvmfs/issues/3628
https://ggus.eu/index.php?mode=ticket_info&ticket_id=167502

**Comment by deesto** [comment]
We had a SL7 old client WN hang yesterday, detailed [here](https://github.com/cvmfs/cvmfs/issues/3628#issuecomment-2215522356). This is just a mention and IMO not worth looking into further, as I believe it was a very long running WN whose cache almost filled, and on which a `wipecache` action was sufficient to revive ATLAS repos.

**Comment by deesto** [comment]
Dave and Valentin continue to help debug recurring client issues at AGLT2 (via email thread). The most recent issues may be related to some local, automated process (always running at :05 past the hour) interfering with the CVMFS watchdog process's normal repo unmounts, or a very short time-out value (45s) on autofs mounts.

**Comment by deesto** [comment]
Paul closed [an ATLAS PanDA Jira ticket](https://its.cern.ch/jira/browse/ATLASPANDA-998) discussing potential improvements to pilot checks for CVMFS repo mounts, most of which have been implemented.

**Comment by deesto** [comment]
If you're following this issue, you may want a look at [this update](https://github.com/cvmfs/cvmfs/issues/3628#issuecomment-2278520857), as there appears to be a possible correlation between these ATLAS client issues and WN segfaults in athena and MemoryMonitor.

**Comment by mlassnig** [comment]
Hi, are there any updates related to this? Have these issues been resolved by now?

**Comment by deesto** [comment]
@mlassnig Very much still ongoing but promising developments as mentioned [here](https://github.com/cvmfs/cvmfs/issues/3628).

**Comment by deesto** [comment]
Anyone interested in these issues should note the new report that we've branched off from our most recent findings, here:
https://github.com/cvmfs/cvmfs/issues/3659

It would be nice if sites other than mine would continue to add information here about issues they're still having, as centralizing our debugging and testing was largely the point.

And for ATLAS: it seems many of these jobs are trying to request files from the `projects.cern.ch` repo, which is intentionally restricted to CERN access only (by CERN) and ends up peppering all other WN sites' client logs with "failure" errors that make debugging actual issues a bit more difficult. Would it be possible to find which users/jobs are requesting these files, and ask them nicely (or not) to run those jobs at CERN only?

**Comment by rptaylor** [comment]
> the `projects.cern.ch` repo, which is intentionally restricted to CERN access only

We have a similar situation with a repository of restricted (licensed) software, for which we do this: 
https://github.com/cvmfs-contrib/config-repo/blob/default/etc/cvmfs/config.d/restricted.computecanada.ca.conf#L3

It's not very nice, but still nicer than trying futilely to access something that should not be accessed, waiting for a timeout, filling the logs with spurious errors, etc. What would be most nice would be a way to cleanly disable or block a repo (other than CVMFS_STRICT_MOUNT) to prevent the client from attempting to connect in the first place, and expose some sort of error to the user indicating it is administratively disabled (permission denied?).

**Comment by deesto** [comment]
I'm closing this, given the reported issues are largely mitigated by code in the latest release (2.11.5), with the known caveat that nodes should completely wipe their caches and/or kill all existing CVMFS client connections and/or reboot nodes after upgrading to this release. Also due to the disappointing lack of participation here from other ATLAS sites, with the exception of Ryan's tip of mitigating issues with unauthorized access of the `projects` repo, which is appreciated but not related to the crux of this ticket.
