### ISSUE TITLE
FSKit support

### ISSUE THREAD

**Issue by ktf** [cvmfs/cvmfs#3620]
In case you guys didn't see this:

https://github.com/KhaosT/FSKitSample

**Comment by vvolkl** [comment]
Very interesting, thanks Giulio! We're still hoping to be able to use the FUSE API also on MacOS. Everything else would require significant effort and maintenance. Fuse-t seems to let us avoid that and looks like it works well enough to base CVMFS on for now.

**Comment by vvolkl** [comment]
Discussions on FSkit are ongoing for both fuse-t ( www.github.com/macos-fuse-t/fuse-t/issues/69 ) and osxfuse ( www.github.com/osxfuse/osxfuse/issues/1025 ). Hopefully one of those will be re-implemented using FSKit,  letting us keep using the Fuse-API . FSKit is still only available in beta releases of MacOS, so still unstable, meaning that  that might anyway still take some time.
