### ISSUE TITLE
The OSX package file is missing for cvmfs-2.11.4

### ISSUE THREAD

**Issue by cwwalter** [cvmfs/cvmfs#3647]
There is no package file listed in https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.11.4/

**Comment by vvolkl** [comment]
Thansks for the report! Now fixed. With the next release, we'll switch to a different libfuse implementation on macos, so this was missing in the build infrastructure.

**Comment by cwwalter** [comment]
Thank you! That's great.

BTW, do you think it might be possible for MacOS to have a homebrew cask entry for the pkg?  That would make it much easier to keep up with releases etc.

**Comment by vvolkl** [comment]
Thanks for the suggestion, I'll look into that!
