### ISSUE TITLE
cvmfs_server fails in kubernetes containers based on supervisord

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3661]
I wanted to do some performance tests of cvmfs_server operations under kubernetes, and at least on the cluster I am using (the OSG Tiger cluster) the containers are based on supervisord instead of systemd.  The cvmfs_server add-replica command failed because of the lack of systemd, and it would be nice to be able to use it there.

**Comment by maxnoe** [comment]
Reading the current lines concerned with this:

https://github.com/cvmfs/cvmfs/blob/f18b70a15f2cfacfb62264e3861d58eb1b0d9878/cvmfs/server/cvmfs_server_coda.sh#L82-L97

It seems to me like this setup would still fail when `systemctl` is not availble, as it would trigger the `die` in line 95 also in cases where `supervisorctl` was found

**Comment by DrDaveD** [comment]
You're right but are you aware of such a case?  Most containers are based on standard distros which have either systemctl or service.
