### ISSUE TITLE
Support CVMFS_EXTERNAL_METALINK

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs/cvmfs#3668]
Currently, a list of servers in CVMFS_EXTERNAL_URL is geosorted in order to locate caches for repositories that use external data.  The [OSG pelican project](https://pelicanplatform.org/) now supplies an alternative method for locating and sorting the caches, based on the [RFC 6249 Metalink/HTTP standard](https://www.ietf.org/rfc/rfc6249.txt).  The pelican server acts as a redirector and includes an http `Link` header which includes an ordered list of caches.  @bbockelm suggested in his [CernVM workshop 2024 talk (page 32)](https://indico.cern.ch/event/1347727/timetable/#23-pelican-and-the-open-scienc) to implement CVMFS_EXTERNAL_METALINK as a list of URLs of such redirectors.  In order to work with a mix of old clients that do not recognize it and new clients that do, when CVMFS_EXTERNAL_METALINK is set then it should take priority and cause CVMFS_EXTERNAL_URL to be ignored.

**Comment by bbockelm** [comment]
Random thoughts on this:
1.  The metalink standard indicates how far up the hierarchy the mirroring goes; can be used as a way to determine how much of the namespace the response could be used for.
2. Alternately, one could just assume the link response is good for the entire contents of the repository.  Much simpler -- but somewhat limiting (as Pelican is considering tweaking the responses based on cache contents).
3. How long should the response be cached for?  Definitely not for the duration of the mount; I was thinking on the order of 15 minutes.

**Comment by DrDaveD** [comment]
I think it would be much too complicated to keep track of different responses for parts of a repository so I hope we don't have to go that way.

Let's have a parameter that determines how long to cache the response for.  If zero, then every request will be looked up, much like the way dCache does a redirect on every request except that there's a list of servers to try in case of timeout or failure.  I think 5 minutes is a good default, like other things related to retries in CVMFS for example the time for when lists of proxies are reset to the beginning after failures.
