### ISSUE TITLE
Problem with installation on Fedora Laptop

### ISSUE THREAD

**Issue by danielsentenac** [cvmfs/cvmfs#3697]
Hi,

it is impossible to install CVMFS on fedora:

dnf install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
Error: 
 Problem: conflicting requests
  - nothing provides redhat-release >= 5 needed by cvmfs-release-3-2.noarch
(try to add '--skip-broken' to skip uninstallable packages)

I tried directly from the cvfms  repo where only FC 34, 38 40 are available. I could not install one of these on my FC 36.

Could you solve this issue ?
Thanks,

**Comment by vvolkl** [comment]
Discussed in https://cernvm-forum.cern.ch/t/cvmfs-installation-on-fedora-36/505/4
