### ISSUE TITLE
Connection issues to webpage and package server

### ISSUE THREAD

**Issue by maxnoe** [cvmfs/cvmfs#3698]
Today, we started seeing CI failures due to connection issues to 

* https://ecsft.cern.ch/

for `dnf isntall -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm`

The same issues seem to also affect the web page:

* https://cernvm.cern.ch/fs/

Which is probably unsurprising, since they resolve to the same host:

```
❯ nslookup cernvm.cern.ch
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
cernvm.cern.ch	canonical name = cernvm-lb.cern.ch.
Name:	cernvm-lb.cern.ch
Address: 188.184.97.7

❯ nslookup ecsft.cern.ch
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
ecsft.cern.ch	canonical name = cernvm-lb.cern.ch.
Name:	cernvm-lb.cern.ch
Address: 188.184.97.7
```

The error messages changed somewhat over the day, we saw:

* SSL_ERROR_NO_CYPHER_OVERLAP
* connection timeout
* connection refused
* SSL_ERROR_RX_RECORD_TOO_LONG

the last one is the current error

**Comment by vvolkl** [comment]
Hi @maxnoe , apologies for that, that was an upgrade gone wrong. Our proxy is reverted, which means that it should work  except for an issue with https urls on firefox. To fix that, I'll have to do another upgrade next week, which again means ~1h of downtime.

**Comment by cwwalter** [comment]
Hi All,

Just to let you know I also (still) see this on both Safari and Firefox on MacOS.  Interestingly, it is OK on macOS Sonoma, but not Sequoia.

**Comment by vvolkl** [comment]
Server Upgrade completed, this should now be OK on all browsers.

**Comment by cwwalter** [comment]
I can confirm that the site is now reachable on MacOS Sequoia with both Safari and Firefox.
